import type { GraphMode } from "./types";

/** Example queries per mode — 2 are randomly picked on each mode switch. */
export const MODE_EXAMPLES: Record<GraphMode, string[]> = {
  ask: [
    "What pathways connect dopamine to schizophrenia?",
    "Summarize recent findings on BDNF and depression",
    "Compare SSRI and SNRI mechanisms of action",
    "What role does neuroinflammation play in Alzheimer's?",
    "How does the gut-brain axis influence mood disorders?",
    "What are the genetic risk factors for bipolar disorder?",
    "Explain the relationship between tau and amyloid-beta",
    "What evidence supports ketamine for treatment-resistant depression?",
    "How do antipsychotics affect dopamine D2 receptors?",
    "What is the role of microglia in neurodegeneration?",
    "Describe the serotonin hypothesis of depression",
    "What are the latest advances in optogenetics research?",
    "How does chronic stress alter hippocampal neurogenesis?",
    "What links sleep disruption to psychiatric illness?",
    "Compare glutamate and GABA signaling in epilepsy",
    "What is the kynurenine pathway's role in depression?",
    "How do cannabinoid receptors modulate pain?",
    "What distinguishes vascular dementia from Alzheimer's?",
    "How does lithium exert neuroprotective effects?",
    "What is the role of orexin in narcolepsy?",
    "How do mirror neurons contribute to empathy?",
    "What mechanisms underlie deep brain stimulation?",
    "How does epigenetics influence addiction vulnerability?",
    "What is the glymphatic system and why does it matter?",
    "Compare typical and atypical antipsychotic mechanisms",
    "How does cortisol affect prefrontal cortex function?",
    "What is the cholinergic hypothesis of Alzheimer's?",
    "How do triptans work for migraine?",
    "What are the neurobiology findings in PTSD?",
    "How does vagus nerve stimulation affect depression?",
    "What role do exosomes play in neurodegeneration?",
    "How does the cerebellum contribute to cognition?",
    "What links autoimmunity to psychiatric symptoms?",
    "How do monoamine oxidase inhibitors work?",
    "What is the role of NMDA receptors in memory?",
    "How does prenatal stress affect neurodevelopment?",
    "What are the mechanisms of opioid tolerance?",
    "How does neuroinflammation contribute to chronic pain?",
    "What is the role of GABA-B receptors in anxiety?",
    "Compare transcranial direct current and magnetic stimulation",
    "What metabolic changes occur in major depression?",
    "How do gap junctions contribute to seizure propagation?",
    "What is the role of the insula in interoception?",
    "How does the locus coeruleus regulate arousal?",
    "What are the molecular targets of psychedelics?",
    "How does adult hippocampal neurogenesis affect learning?",
    "What is the striatal dopamine hypothesis of schizophrenia?",
    "How do clock genes influence circadian rhythms?",
    "What role does CREB play in long-term memory?",
    "How does alpha-synuclein spread in Parkinson's disease?",
  ],
  explore: [
    "Show clusters related to neuroinflammation",
    "Find connections between GABA and anxiety",
    "Which papers discuss the default mode network?",
    "Map the overlap between depression and pain research",
    "What clusters mention CRISPR applications in neuroscience?",
    "Show papers linking oxidative stress to Parkinson's",
    "Find the most cited authors on synaptic plasticity",
    "Which journals dominate the PTSD literature?",
    "Explore connections between sleep and memory consolidation",
    "Show recent work on psychedelic-assisted therapy",
    "Find clusters at the intersection of AI and neuroimaging",
    "Which sections discuss methodology most frequently?",
    "Show the largest cluster and its top papers",
    "Find papers that mention both serotonin and dopamine",
    "Which clusters overlap between addiction and reward?",
    "Show papers published in the last two years on TMS",
    "Find connections between gut microbiome and behavior",
    "Map the network of papers on treatment-resistant depression",
    "Which clusters discuss pharmacogenomics?",
    "Show the distribution of paper sections across clusters",
    "Find papers that bridge neurology and psychiatry",
    "Which clusters contain the most review articles?",
    "Show connections between neuroimaging and biomarkers",
    "Find papers on pediatric epilepsy management",
    "Map research trends in ketamine and esketamine",
    "Which authors appear across multiple clusters?",
    "Show papers discussing blood-brain barrier permeability",
    "Find the most recent papers on tau immunotherapy",
    "Explore the cluster structure of pain research",
    "Which papers discuss both genetics and epigenetics?",
    "Show connections between anxiety disorders and HPA axis",
    "Find papers on wearable devices in neurology",
    "Map the overlap between autism and ADHD research",
    "Which clusters discuss clinical trial methodology?",
    "Show research on brain-computer interfaces",
    "Find papers linking vitamin D to neurological outcomes",
    "Explore the network of neuroimmunology research",
    "Which clusters contain case reports?",
    "Show the most connected papers in the graph",
    "Find research on digital phenotyping in psychiatry",
    "Map connections between stroke and neuroplasticity",
    "Which papers discuss both MRI and PET imaging?",
    "Show clusters related to neurodevelopmental disorders",
    "Find papers on cannabidiol and seizure control",
    "Explore connections between aging and cognitive decline",
    "Which clusters discuss precision medicine approaches?",
    "Show the timeline of deep brain stimulation research",
    "Find papers that cite landmark schizophrenia studies",
    "Map the overlap between inflammation and mood disorders",
    "Which sections most frequently discuss limitations?",
  ],
  learn: [
    "Explain the HPA axis in simple terms",
    "What is long-term potentiation?",
    "How do benzodiazepines work?",
    "Teach me about the blood-brain barrier",
    "What is the difference between gray and white matter?",
    "Explain how action potentials propagate",
    "What is the mesolimbic reward pathway?",
    "How does myelination affect signal speed?",
    "Describe the role of astrocytes in the CNS",
    "What is excitotoxicity and why does it matter?",
    "Explain the concept of neural oscillations",
    "What happens during a seizure at the cellular level?",
    "How do SSRIs increase serotonin availability?",
    "Describe the stages of Alzheimer's disease progression",
    "What are the basal ganglia and what do they do?",
    "Explain the difference between white and gray matter",
    "How does the thalamus relay sensory information?",
    "What is Wernicke's area and what does it process?",
    "Explain the concept of receptor downregulation",
    "What is the difference between apoptosis and necrosis?",
    "How do second messenger systems work in neurons?",
    "Explain the role of the prefrontal cortex in decision-making",
    "What is the difference between MRI and fMRI?",
    "How does the immune system interact with the brain?",
    "Explain the concept of synaptic pruning",
    "What is the role of dopamine in Parkinson's disease?",
    "How do ion channels control neuronal excitability?",
    "What is the difference between afferent and efferent nerves?",
    "Explain how neurotransmitter reuptake works",
    "What are Brodmann areas and how are they used?",
    "How does the amygdala process fear responses?",
    "What is the role of serotonin in sleep regulation?",
    "Explain the blood-CSF barrier vs the blood-brain barrier",
    "What is cortical spreading depression in migraine?",
    "How do voltage-gated sodium channels work?",
    "What is the difference between agonist and antagonist drugs?",
    "Explain how EEG measures brain activity",
    "What is the role of the hippocampus in spatial memory?",
    "How does chronic pain rewire the brain?",
    "What are the main types of glial cells?",
    "Explain the concept of hemispheric lateralization",
    "What is the role of acetylcholine in cognition?",
    "How does the cerebellum coordinate movement?",
    "What is the difference between tolerance and dependence?",
    "Explain the trigeminal nerve and its role in headache",
    "What is the default mode network?",
    "How do neurotrophic factors support neuron survival?",
    "What is the connectome and why is it studied?",
    "Explain the concept of long-term depression in synapses",
    "What role does norepinephrine play in attention?",
  ],
  write: [
    "Draft a literature review on ketamine for depression",
    "Outline a case report on treatment-resistant OCD",
    "Summarize key findings for a manuscript discussion",
    "Write an introduction for a paper on neuroplasticity",
    "Draft a methods section for a systematic review",
    "Compose an abstract on dopamine transporter imaging",
    "Write a clinical vignette about first-episode psychosis",
    "Outline a grant proposal on neuromodulation therapies",
    "Draft a patient education handout on epilepsy",
    "Summarize the limitations of current biomarker research",
    "Write a discussion section comparing two treatment arms",
    "Compose a brief review on transcranial magnetic stimulation",
    "Draft a conclusion for a meta-analysis on antidepressants",
    "Write a letter to the editor about psychedelic research",
    "Outline a review paper on the gut-brain axis",
    "Draft a study rationale for an ADHD clinical trial",
    "Compose a figure legend for a brain connectivity diagram",
    "Write a background section on circadian rhythm disruption",
    "Draft a results narrative for a neuroimaging study",
    "Outline a textbook chapter on anxiety neurobiology",
    "Write a comparative analysis of two antiepileptic drugs",
    "Draft talking points for a conference poster presentation",
    "Compose an ethics section for a brain stimulation protocol",
    "Write a summary table of cognitive assessment instruments",
    "Draft a research question for a sleep study",
    "Outline a review on biomarkers for early Alzheimer's",
    "Write a paragraph on the history of antipsychotic drugs",
    "Compose a lay summary of a genetics study for patients",
    "Draft a clinical significance statement for a pain trial",
    "Write a rebuttal to a reviewer comment on methodology",
    "Outline a perspective piece on AI in psychiatric diagnosis",
    "Draft a section on adverse effects of immunotherapy",
    "Write a comparison of screening tools for depression",
    "Compose an introduction on the opioid crisis and policy",
    "Draft a protocol summary for an observational cohort study",
    "Write a brief commentary on reproducibility in neuroscience",
    "Outline a narrative review on migraine pathophysiology",
    "Draft a table of inclusion and exclusion criteria",
    "Compose a cover letter for a journal submission",
    "Write a limitations paragraph for a case-control study",
    "Draft a clinical pearl on medication-induced movement disorders",
    "Outline a paper on telemedicine in neurological practice",
    "Write an informed consent summary for a research participant",
    "Draft a brief review on neurostimulation for chronic pain",
    "Compose a discussion of off-label prescribing evidence",
    "Write a teaching case on autoimmune encephalitis workup",
    "Draft a quality improvement proposal for stroke outcomes",
    "Outline a commentary on mental health equity",
    "Write a synthesis of evidence on exercise and cognition",
    "Draft a progress note template for a neurology rotation",
  ],
};

/** Pick n random items from an array (Fisher-Yates partial shuffle). */
export function pickRandom<T>(arr: T[], n: number): T[] {
  const copy = [...arr];
  const count = Math.min(n, copy.length);
  for (let i = 0; i < count; i++) {
    const j = i + Math.floor(Math.random() * (copy.length - i));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, count);
}
