from __future__ import annotations


DOCUMENT_SOURCE_KIND_PUBTATOR_BIOCXML = 1
DOCUMENT_SOURCE_KIND_S2ORC_ANNOTATION = 2
DOCUMENT_SOURCE_KIND_PMC_BIOC = 3
DOCUMENT_SOURCE_KIND_OTHER = 4

SOURCE_PRIORITY_PMC_BIOC = 5
SOURCE_PRIORITY_S2ORC = 10

TEXT_AVAILABILITY_NONE = 0
TEXT_AVAILABILITY_ABSTRACT = 1
TEXT_AVAILABILITY_FULLTEXT = 2

SECTION_ROLE_UNKNOWN = 0
SECTION_ROLE_ABSTRACT = 1
SECTION_ROLE_INTRODUCTION = 2
SECTION_ROLE_METHODS = 3
SECTION_ROLE_RESULTS = 4
SECTION_ROLE_DISCUSSION = 5
SECTION_ROLE_CONCLUSION = 6
SECTION_ROLE_SUPPLEMENT = 7
SECTION_ROLE_OTHER = 8

BLOCK_KIND_PARAGRAPH = 1
BLOCK_KIND_FIGURE_CAPTION = 2
BLOCK_KIND_TABLE_CAPTION = 3
BLOCK_KIND_TABLE_BODY_TEXT = 4
BLOCK_KIND_STRUCTURED = 5
BLOCK_KIND_METADATA = 6
BLOCK_KIND_OTHER = 7

SEGMENTATION_SOURCE_S2ORC_ANNOTATION = 1
SEGMENTATION_SOURCE_STANZA_BIOMEDICAL = 2
SEGMENTATION_SOURCE_SYNTOK = 3
SEGMENTATION_SOURCE_DETERMINISTIC_FALLBACK = 4
