import { buildGraphData } from '@/lib/graph/transform'

describe('buildGraphData', () => {
  it('shapes bundle-first graph rows into graph data and computes stats', () => {
    const data = buildGraphData({
      points: [
        {
          id: 'chunk-1',
          node_id: 'chunk-1',
          paper_id: 'paper-1',
          x: 1,
          y: 2,
          cluster_id: 3,
          cluster_label: 'Neuroinflammation',
          cluster_probability: 0.92,
          outlier_score: 0.1,
          citekey: 'Paper2026',
          title: 'A paper',
          year: 2026,
          journal: 'Journal A',
          doi: '10.1000/a',
          pmid: 123456,
          pmcid: null,
          stable_chunk_id: 'stable-1',
          chunk_index: 1,
          section_type: 'Methods',
          section_canonical: 'Methods',
          section_path: '["Methods"]',
          page_number: 3,
          token_count: 120,
          char_count: 640,
          chunk_kind: 'paragraph',
          block_type: 'marker_block',
          block_id: 'block-1',
          chunk_preview: 'Representative chunk',
          paper_author_count: 4,
          paper_reference_count: 23,
          paper_asset_count: 2,
          paper_chunk_count: 12,
          paper_entity_count: '8',
          paper_relation_count: '5',
          paper_sentence_count: 78,
          paper_page_count: 6,
          paper_table_count: 1,
          paper_figure_count: 0,
          has_table_context: false,
          has_figure_context: true,
        },
        {
          id: 'chunk-2',
          node_id: 'chunk-2',
          paper_id: 'paper-2',
          x: 3,
          y: 4,
          cluster_id: 0,
          cluster_label: null,
          cluster_probability: 0.21,
          outlier_score: 0.7,
          title: 'Another paper',
          citekey: 'PaperTwo2026',
          year: 2025,
          journal: null,
          doi: null,
          pmid: null,
          pmcid: null,
          stable_chunk_id: null,
          chunk_index: 2,
          section_type: null,
          section_canonical: null,
          section_path: null,
          page_number: null,
          token_count: null,
          char_count: null,
          chunk_kind: null,
          block_type: null,
          block_id: null,
          chunk_preview: null,
          paper_author_count: null,
          paper_reference_count: null,
          paper_asset_count: null,
          paper_chunk_count: null,
          paper_entity_count: null,
          paper_relation_count: null,
          paper_sentence_count: null,
          paper_page_count: null,
          paper_table_count: null,
          paper_figure_count: null,
          has_table_context: null,
          has_figure_context: null,
        },
      ],
      clusters: [
        {
          cluster_id: 0,
          label: 'Noise',
          label_mode: null,
          label_source: null,
          member_count: 1,
          centroid_x: 0,
          centroid_y: 0,
          representative_rag_chunk_id: null,
          candidate_count: null,
          entity_candidate_count: null,
          lexical_candidate_count: null,
          mean_cluster_probability: null,
          mean_outlier_score: null,
          paper_count: 1,
          is_noise: true,
        },
        {
          cluster_id: 3,
          label: 'Neuroinflammation',
          label_mode: 'lexical',
          label_source: 'keywords',
          member_count: 12,
          centroid_x: 10,
          centroid_y: 20,
          representative_rag_chunk_id: 'chunk-1',
          candidate_count: 4,
          entity_candidate_count: 1,
          lexical_candidate_count: 3,
          mean_cluster_probability: 0.92,
          mean_outlier_score: 0.1,
          paper_count: 1,
          is_noise: false,
        },
      ],
      facets: [
        {
          facet_name: 'year',
          facet_value: '2026',
          facet_label: '2026',
          point_count: 1,
          paper_count: 1,
          cluster_count: 1,
          sort_key: '2026',
        },
      ],
    })

    expect(data.nodes).toHaveLength(2)
    expect(data.nodes[0]).toMatchObject({
      index: 0,
      id: 'chunk-1',
      paperTitle: 'A paper',
      citekey: 'Paper2026',
      clusterId: 3,
    })
    expect(data.nodes[1]).toMatchObject({
      index: 1,
      id: 'chunk-2',
      paperTitle: 'Another paper',
      citekey: 'PaperTwo2026',
      clusterId: 0,
    })
    expect(data.stats).toEqual({
      chunks: 2,
      papers: 2,
      clusters: 1,
      noise: 1,
    })
    expect(data.facets).toHaveLength(1)
    expect(data.clusterColors[3]).toMatch(/^#/)
  })
})
