"""SQL query text for the current-table evidence baseline.

This module is the public API surface for all RAG SQL constants.
Implementation is split into private domain modules:

- ``_queries_paper_core``     — foundational SQL fragments (column lists, joins, title pieces)
- ``_queries_paper_search``   — FTS paper search (full-graph, in-selection, in-graph)
- ``_queries_title_lookup``   — multi-strategy title lookup (exact/prefix/KNN)
- ``_queries_chunk_search``   — chunk-level lexical search
- ``_queries_entity_search``  — entity-based paper retrieval
- ``_queries_relation_lookup``— relation-based paper retrieval + direct lookup
- ``_queries_dense_semantic`` — dense vector search, semantic neighbors, citation context

Callers use ``from app.rag import queries`` and access constants as ``queries.XYZ``.
"""

from app.rag._queries_chunk_search import (  # noqa: F401
    CHUNK_SEARCH_IN_SELECTION_SQL,
    CHUNK_SEARCH_SQL,
)
from app.rag._queries_dense_semantic import (  # noqa: F401
    ASSET_LOOKUP_SQL,
    AUTHOR_LOOKUP_SQL,
    CITATION_CONTEXT_SQL,
    DENSE_QUERY_SEARCH_ANN_BROAD_SCOPE_SQL,
    DENSE_QUERY_SEARCH_IN_SELECTION_SQL,
    DENSE_QUERY_SEARCH_SQL,
    ENTITY_MATCH_SQL,
    REFERENCE_LOOKUP_SQL,
    RELATION_MATCH_SQL,
    SCOPE_CORPUS_LOOKUP_BY_CORPUS_ID_SQL,
    SCOPE_CORPUS_LOOKUP_BY_PAPER_ID_SQL,
    SELECTED_CORPUS_LOOKUP_BY_CORPUS_ID_SQL,
    SELECTED_CORPUS_LOOKUP_BY_PAPER_ID_SQL,
    SEMANTIC_NEIGHBOR_ANN_BROAD_SCOPE_SQL,
    SEMANTIC_NEIGHBOR_IN_SELECTION_SQL,
    SEMANTIC_NEIGHBOR_INDEX_LOOKUP_SQL,
    SEMANTIC_NEIGHBOR_SQL,
)
from app.rag._queries_entity_search import (  # noqa: F401
    ENTITY_CANDIDATE_SCORE_SQL,
    ENTITY_EXACT_MATCHES_CTE_SQL,
    ENTITY_FUZZY_MATCHES_CTE_SQL,
    ENTITY_FUZZY_QUERY_TERMS_CTE_SQL,
    ENTITY_GRAPH_SCOPE_CTE_SQL,
    ENTITY_MATCHED_CONCEPTS_CTE_SQL,
    ENTITY_QUERY_TERMS_CTE_SQL,
    ENTITY_RANKED_PAPERS_SELECT_SQL,
    PAPER_ENTITY_EXACT_SEARCH_CURRENT_MAP_SQL,
    PAPER_ENTITY_EXACT_SEARCH_IN_SELECTION_SQL,
    PAPER_ENTITY_EXACT_SEARCH_SQL,
    PAPER_ENTITY_SEARCH_CURRENT_MAP_SQL,
    PAPER_ENTITY_SEARCH_IN_SELECTION_SQL,
    PAPER_ENTITY_SEARCH_SQL,
)
from app.rag._queries_metadata_search import (  # noqa: F401
    PAPER_AUTHOR_YEAR_SEARCH_CURRENT_MAP_SQL,
    PAPER_AUTHOR_YEAR_SEARCH_IN_SELECTION_SQL,
    PAPER_AUTHOR_YEAR_SEARCH_SQL,
    PAPER_JOURNAL_YEAR_SEARCH_CURRENT_MAP_SQL,
    PAPER_JOURNAL_YEAR_SEARCH_IN_SELECTION_SQL,
    PAPER_JOURNAL_YEAR_SEARCH_SQL,
    PAPER_METADATA_SEARCH_CURRENT_MAP_SQL,
    PAPER_METADATA_SEARCH_IN_SELECTION_SQL,
    PAPER_METADATA_SEARCH_SQL,
    PAPER_PUBLICATION_TYPE_TOPIC_SEARCH_CURRENT_MAP_SQL,
    PAPER_PUBLICATION_TYPE_TOPIC_SEARCH_IN_SELECTION_SQL,
    PAPER_PUBLICATION_TYPE_TOPIC_SEARCH_SQL,
)
from app.rag._queries_paper_core import (  # noqa: F401
    CHUNK_EXACT_MATCH_BONUS,
    CHUNK_EXACT_MATCH_NORMALIZATION_REGEX,
    CHUNK_HEADLINE_OPTIONS,
    CHUNK_SEARCH_VECTOR_SQL,
    EMBEDDED_PAPER_COUNT_ESTIMATE_SQL,
    ENTITY_FUZZY_SIMILARITY_THRESHOLD,
    ENTITY_MENTION_CONCEPT_KEY_SQL,
    ENTITY_MENTION_TYPE_KEY_SQL,
    ENTITY_TABLE_CONCEPT_KEY_SQL,
    ENTITY_TABLE_TYPE_KEY_SQL,
    ENTITY_TOP_CONCEPTS_PER_TERM,
    GRAPH_INPUT_CTE_SQL,
    PAPER_CORE_JOINS,
    PAPER_EMBEDDING_LITERAL_SQL,
    PAPER_GRAPH_JOIN_SQL,
    PAPER_GRAPH_WHERE_SQL,
    PAPER_NORMALIZED_TITLE_KEY_SQL,
    PAPER_NORMALIZED_TITLE_SIMILARITY_SQL,
    PAPER_SEARCH_VECTOR_SQL,
    PAPER_SELECT_COLUMNS,
    PAPER_TITLE_SIMILARITY_SQL,
    PAPER_TITLE_TEXT_SQL,
    QUERY_ENTITY_TERM_MATCH_SQL,
    QUERY_VOCAB_CONCEPT_MATCH_SQL,
    RANKED_PAPER_SELECT_COLUMNS,
    SPECIES_PROFILE_SQL,
)
from app.rag._queries_paper_search import (  # noqa: F401
    PAPER_SEARCH_IN_GRAPH_SQL,
    PAPER_SEARCH_IN_SELECTION_SQL,
    PAPER_SEARCH_SQL,
    PAPER_SEARCH_SQL_NO_TITLE_SIMILARITY,
    PAPER_TITLE_FTS_CANDIDATE_SQL,
    PAPER_TITLE_NORMALIZED_EXACT_CANDIDATE_SQL,
    PAPER_TITLE_NORMALIZED_PREFIX_CANDIDATE_SQL,
    PAPER_TITLE_TEXT_EXACT_CANDIDATE_SQL,
    PAPER_TITLE_TEXT_PREFIX_CANDIDATE_SQL,
)
from app.rag._queries_relation_lookup import (  # noqa: F401
    PAPER_LOOKUP_DIRECT_SQL,
    PAPER_LOOKUP_SQL,
    PAPER_RELATION_SEARCH_CURRENT_MAP_SQL,
    PAPER_RELATION_SEARCH_IN_SELECTION_SQL,
    PAPER_RELATION_SEARCH_SQL,
)
from app.rag._queries_title_lookup import (  # noqa: F401
    PAPER_TITLE_LOOKUP_IN_GRAPH_SQL,
    PAPER_TITLE_LOOKUP_SQL,
)
