import type { GraphNodeBase } from './nodes'

export type GraphMode = 'ask' | 'explore' | 'learn' | 'create'

export type MapLayer = 'chunk' | 'paper' | 'geo'

export type ColorTheme = 'light' | 'dark'
export type PointColorStrategy = 'categorical' | 'continuous' | 'direct' | 'single'
export type PointSizeStrategy = 'auto' | 'direct' | 'single'
export type ColorSchemeName =
  | 'seasons'
  | 'candy'
  | 'easy'
  | 'default'
  | 'warm'
  | 'evening'
  | 'bombay'
  | 'koi'
  | 'august'
  | 'scenery'
  | 'mango'
  | 'ember'
  | 'cranberry'
  | 'autumn'
  | 'dream'
  | 'vitamins'
  | 'confetti'
  | 'rainbow'
  | 'crayons'
  | 'vivid'
  | 'timo'
  | 'tropical'
  | 'tulips'
  | 'forestlake'
  | 'enchant'
  | 'woop'
  | 'unicorn'
  | 'tolvibrant'
  | 'bright'
  | 'vibrant'
  | 'okabeito'
  | 'tableau10'
  | 'tailoring'
  | 'vibrant2'
  | 'spectral'
  | 'classic'
  | 'royal'
  | 'warm2'
  | 'twilight'
  | 'turbo'
  | 'cool'
  | 'viridis'
  | 'plasma'

export type FilterableColumnKey =
  | Exclude<keyof GraphNodeBase, 'index' | 'color' | 'colorLight'>
  | 'nodeKind'
  | 'sectionCanonical'
  | 'chunkKind'
  | 'pageNumber'
  | 'tokenCount'
  | 'hasTableContext'
  | 'hasFigureContext'
  | 'institution'
  | 'country'
  | 'countryCode'
  | 'city'
  | 'region'
  | 'rorId'
  | 'authorCount'
  | 'semanticGroups'
  | 'organSystems'
  | 'topEntities'
  | 'relationCategories'
  | 'textAvailability'
  | 'isOpenAccess'
  | 'hasOpenAccessPdf'
  | 'paperAuthorCount'
  | 'paperReferenceCount'
  | 'paperAssetCount'
  | 'paperEntityCount'
  | 'paperRelationCount'

export type NumericColumnKey =
  | 'clusterProbability'
  | 'year'
  | 'pageNumber'
  | 'tokenCount'
  | 'mentionCount'
  | 'paperCount'
  | 'chunkCount'
  | 'relationCount'
  | 'aliasCount'
  | 'aliasQualityScore'
  | 'authorCount'
  | 'paperAuthorCount'
  | 'paperReferenceCount'
  | 'paperAssetCount'
  | 'paperEntityCount'
  | 'paperRelationCount'
  | 'x'
  | 'y'

export type DataColumnKey = FilterableColumnKey

export type SizeColumnKey = 'none' | NumericColumnKey
