SET ROLE engine_warehouse_admin;

CREATE TABLE IF NOT EXISTS solemd.paper_entity_signal_builds (
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pt3_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    entity_signal_checksum TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'building',
    row_count BIGINT,
    byte_size BIGINT,
    detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    PRIMARY KEY (
        s2_source_release_id,
        pt3_source_release_id,
        entity_signal_checksum
    ),
    CONSTRAINT ck_paper_entity_signal_builds_status
        CHECK (status IN ('building', 'complete', 'failed', 'stale'))
);
ALTER TABLE solemd.paper_entity_signal_builds SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.paper_entity_signals (
    paper_entity_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pt3_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    entity_signal_checksum TEXT NOT NULL,
    paper_id TEXT NOT NULL,
    pmid INTEGER NOT NULL,
    entity_type SMALLINT NOT NULL,
    concept_id_raw TEXT NOT NULL,
    term_id UUID,
    term_canonical_name TEXT,
    term_category TEXT,
    matched_alias TEXT,
    rule_canonical_name TEXT,
    rule_family_key TEXT,
    rule_confidence TEXT,
    rule_min_reference_count INTEGER NOT NULL DEFAULT 0,
    matched_mention_text TEXT,
    signal_count INTEGER NOT NULL,
    reference_out_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_paper_entity_signals_match
        CHECK (
            (term_id IS NOT NULL AND rule_family_key IS NULL)
            OR (term_id IS NULL AND rule_family_key IS NOT NULL)
        ),
    CONSTRAINT ck_paper_entity_signals_signal_count
        CHECK (signal_count >= 1),
    CONSTRAINT ck_paper_entity_signals_reference_out_count
        CHECK (reference_out_count >= 0),
    CONSTRAINT ck_paper_entity_signals_rule_min_reference_count
        CHECK (rule_min_reference_count >= 0)
);
ALTER TABLE solemd.paper_entity_signals SET (fillfactor = 100);
ALTER TABLE solemd.paper_entity_signals ALTER COLUMN concept_id_raw SET COMPRESSION lz4;
ALTER TABLE solemd.paper_entity_signals ALTER COLUMN matched_mention_text SET COMPRESSION lz4;

CREATE INDEX IF NOT EXISTS idx_paper_entity_signal_builds_status
    ON solemd.paper_entity_signal_builds (status, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_paper_entity_signals_build_paper
    ON solemd.paper_entity_signals (
        s2_source_release_id,
        pt3_source_release_id,
        entity_signal_checksum,
        paper_id
    );
CREATE INDEX IF NOT EXISTS idx_paper_entity_signals_build_term
    ON solemd.paper_entity_signals (
        s2_source_release_id,
        pt3_source_release_id,
        entity_signal_checksum,
        term_id,
        paper_id
    )
    WHERE term_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_paper_entity_signals_build_rule
    ON solemd.paper_entity_signals (
        s2_source_release_id,
        pt3_source_release_id,
        entity_signal_checksum,
        rule_family_key,
        paper_id
    )
    WHERE rule_family_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_paper_entity_signals_vocab
    ON solemd.paper_entity_signals (
        s2_source_release_id,
        pt3_source_release_id,
        entity_signal_checksum,
        paper_id,
        entity_type,
        concept_id_raw,
        term_id
    )
    WHERE term_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_paper_entity_signals_rule
    ON solemd.paper_entity_signals (
        s2_source_release_id,
        pt3_source_release_id,
        entity_signal_checksum,
        paper_id,
        entity_type,
        concept_id_raw,
        rule_family_key
    )
    WHERE rule_family_key IS NOT NULL;

GRANT INSERT, UPDATE, SELECT, DELETE ON TABLE
    solemd.paper_entity_signal_builds,
    solemd.paper_entity_signals
TO engine_ingest_write;

GRANT SELECT ON TABLE
    solemd.paper_entity_signal_builds,
    solemd.paper_entity_signals
TO engine_warehouse_read;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA solemd TO engine_ingest_write;

COMMENT ON TABLE solemd.paper_entity_signal_builds IS
    'Logged build ledger for durable paper-level curated entity signals keyed by S2 release, PT3 release, and entity asset checksum.';
COMMENT ON TABLE solemd.paper_entity_signals IS
    'Durable paper-level curated entity signal layer reused by corpus admission, mapped promotion, and selection summaries. Each row is either a vocab/alias hit or an entity-rule hit.';
COMMENT ON COLUMN solemd.paper_entity_signals.entity_signal_checksum IS
    'Checksum over the vocab term, vocab alias, and entity-rule assets that produced this signal row.';

RESET ROLE;
