SET ROLE engine_warehouse_admin;

CREATE OR REPLACE FUNCTION solemd.clean_venue(input_text TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
RETURNS NULL ON NULL INPUT
AS $$
    SELECT NULLIF(
        trim(
            regexp_replace(
                regexp_replace(
                    regexp_replace(
                        regexp_replace(lower(btrim(input_text)), '\.$', ''),
                        '^\s*the\s+', ''
                    ),
                    '\s*:\s+.*$', ''
                ),
                '\s*\(.*?\)\s*$', ''
            )
        ),
        ''
    );
$$;

CREATE TABLE IF NOT EXISTS solemd.vocab_terms (
    term_id UUID PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    normalized_name TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(canonical_name)
    ) STORED,
    category TEXT NOT NULL,
    umls_cui TEXT,
    rxnorm_cui TEXT,
    semantic_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    semantic_groups TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    organ_systems TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    source_asset_sha256 TEXT NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE solemd.vocab_terms SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.vocab_term_aliases (
    term_id UUID NOT NULL
        REFERENCES solemd.vocab_terms (term_id)
        ON DELETE CASCADE,
    alias TEXT NOT NULL,
    normalized_alias TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(alias)
    ) STORED,
    alias_type TEXT,
    quality_score INTEGER,
    is_preferred BOOLEAN NOT NULL DEFAULT false,
    umls_cui TEXT,
    source_asset_sha256 TEXT NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (term_id, alias)
);
ALTER TABLE solemd.vocab_term_aliases SET (fillfactor = 95);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_runs (
    corpus_selection_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    advisory_lock_key BIGINT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pt3_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    requested_by TEXT,
    trigger TEXT NOT NULL DEFAULT 'manual',
    status SMALLINT NOT NULL DEFAULT 1,
    error_message TEXT,
    last_completed_phase TEXT,
    phases_completed TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    plan_checksum TEXT NOT NULL,
    plan_manifest JSONB NOT NULL,
    phase_started_at JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_corpus_selection_runs_trigger
        CHECK (trigger IN ('manual', 'dispatch')),
    CONSTRAINT ck_corpus_selection_runs_status
        CHECK (status BETWEEN 1 AND 7)
);
ALTER TABLE solemd.corpus_selection_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_signals (
    corpus_selection_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    phase_name TEXT NOT NULL,
    signal_kind TEXT NOT NULL,
    family_key TEXT,
    match_key TEXT,
    match_value TEXT,
    signal_count INTEGER NOT NULL DEFAULT 1,
    contributes_to_candidate BOOLEAN NOT NULL DEFAULT false,
    contributes_to_mapped BOOLEAN NOT NULL DEFAULT false,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_corpus_selection_signals_signal_count
        CHECK (signal_count >= 1)
);
ALTER TABLE solemd.corpus_selection_signals SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.paper_selection_summary (
    corpus_id BIGINT PRIMARY KEY
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    current_status TEXT NOT NULL,
    primary_admission_reason TEXT,
    normalized_venue TEXT NOT NULL DEFAULT '',
    has_journal_match BOOLEAN NOT NULL DEFAULT false,
    has_pattern_match BOOLEAN NOT NULL DEFAULT false,
    has_vocab_entity_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_journal_match BOOLEAN NOT NULL DEFAULT false,
    journal_signal_count INTEGER NOT NULL DEFAULT 0,
    pattern_signal_count INTEGER NOT NULL DEFAULT 0,
    vocab_entity_signal_count INTEGER NOT NULL DEFAULT 0,
    entity_annotation_count INTEGER NOT NULL DEFAULT 0,
    relation_count INTEGER NOT NULL DEFAULT 0,
    mapped_signal_count INTEGER NOT NULL DEFAULT 0,
    mapped_family_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_paper_selection_summary_status
        CHECK (current_status IN ('candidate', 'mapped', 'retired'))
);
ALTER TABLE solemd.paper_selection_summary SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.corpus_wave_runs (
    corpus_wave_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    advisory_lock_key BIGINT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE RESTRICT,
    wave_policy_key TEXT NOT NULL,
    requested_by TEXT,
    status SMALLINT NOT NULL DEFAULT 1,
    error_message TEXT,
    last_completed_phase TEXT,
    phases_completed TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    plan_checksum TEXT NOT NULL,
    plan_manifest JSONB NOT NULL,
    phase_started_at JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_corpus_wave_runs_status
        CHECK (status BETWEEN 1 AND 5)
);
ALTER TABLE solemd.corpus_wave_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.corpus_wave_members (
    corpus_wave_run_id UUID NOT NULL
        REFERENCES solemd.corpus_wave_runs (corpus_wave_run_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    member_ordinal INTEGER NOT NULL,
    enqueued_at TIMESTAMPTZ,
    actor_name TEXT NOT NULL DEFAULT 'hot_text.acquire_for_paper',
    PRIMARY KEY (corpus_wave_run_id, corpus_id),
    CONSTRAINT ck_corpus_wave_members_member_ordinal
        CHECK (member_ordinal >= 1)
);
ALTER TABLE solemd.corpus_wave_members SET (fillfactor = 100);

CREATE INDEX IF NOT EXISTS idx_vocab_terms_normalized_name
    ON solemd.vocab_terms (normalized_name);
CREATE INDEX IF NOT EXISTS idx_vocab_terms_category
    ON solemd.vocab_terms (category);
CREATE INDEX IF NOT EXISTS idx_vocab_terms_umls_cui
    ON solemd.vocab_terms (umls_cui)
    WHERE umls_cui IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_vocab_term_aliases_normalized_alias
    ON solemd.vocab_term_aliases (
        normalized_alias,
        term_id,
        quality_score DESC,
        is_preferred DESC
    );
CREATE INDEX IF NOT EXISTS idx_vocab_term_aliases_umls_cui
    ON solemd.vocab_term_aliases (umls_cui)
    WHERE umls_cui IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_corpus_selection_runs_pair_started
    ON solemd.corpus_selection_runs (
        s2_source_release_id,
        pt3_source_release_id,
        selector_version,
        started_at DESC
    );
CREATE INDEX IF NOT EXISTS idx_corpus_selection_runs_status_started
    ON solemd.corpus_selection_runs (status, started_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_corpus_selection_runs_active_lock
    ON solemd.corpus_selection_runs (advisory_lock_key)
    WHERE advisory_lock_key IS NOT NULL
      AND status BETWEEN 1 AND 5;

CREATE INDEX IF NOT EXISTS idx_corpus_selection_signals_run_corpus
    ON solemd.corpus_selection_signals (corpus_selection_run_id, corpus_id);
CREATE INDEX IF NOT EXISTS idx_corpus_selection_signals_corpus_run
    ON solemd.corpus_selection_signals (corpus_id, corpus_selection_run_id);
CREATE INDEX IF NOT EXISTS idx_corpus_selection_signals_kind_run
    ON solemd.corpus_selection_signals (signal_kind, corpus_selection_run_id);

CREATE INDEX IF NOT EXISTS idx_paper_selection_summary_status_corpus
    ON solemd.paper_selection_summary (current_status, corpus_id);
CREATE INDEX IF NOT EXISTS idx_paper_selection_summary_run_status_corpus
    ON solemd.paper_selection_summary (
        corpus_selection_run_id,
        current_status,
        corpus_id
    );

CREATE INDEX IF NOT EXISTS idx_corpus_wave_runs_selection_started
    ON solemd.corpus_wave_runs (
        corpus_selection_run_id,
        wave_policy_key,
        started_at DESC
    );
CREATE INDEX IF NOT EXISTS idx_corpus_wave_runs_status_started
    ON solemd.corpus_wave_runs (status, started_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_corpus_wave_runs_active_lock
    ON solemd.corpus_wave_runs (advisory_lock_key)
    WHERE advisory_lock_key IS NOT NULL
      AND status BETWEEN 1 AND 3;

CREATE UNIQUE INDEX IF NOT EXISTS uq_corpus_wave_members_order
    ON solemd.corpus_wave_members (corpus_wave_run_id, member_ordinal);
CREATE INDEX IF NOT EXISTS idx_corpus_wave_members_pending
    ON solemd.corpus_wave_members (
        corpus_wave_run_id,
        enqueued_at,
        member_ordinal
    );

CREATE INDEX IF NOT EXISTS idx_s2_papers_raw_release_corpus
    ON solemd.s2_papers_raw (source_release_id, corpus_id)
    WHERE corpus_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pubtator_entity_annotations_release_corpus
    ON pubtator.entity_annotations (source_release_id, corpus_id);
CREATE INDEX IF NOT EXISTS idx_pubtator_relations_release_corpus
    ON pubtator.relations (source_release_id, corpus_id);

COMMENT ON TABLE solemd.vocab_terms IS
    'Curated editorial vocabulary loaded from data/vocab_terms.tsv for corpus selection and later concept derivation.';
COMMENT ON TABLE solemd.vocab_term_aliases IS
    'Curated alias catalog loaded from data/vocab_aliases.tsv and joined against PubTator mention surfaces.';

COMMENT ON TABLE solemd.corpus_selection_runs IS
    'One row per release-pair corpus-selection run that refreshes candidate, mapped, and retired paper membership.';
COMMENT ON TABLE solemd.corpus_selection_signals IS
    'Durable per-paper selection signal ledger keyed to one corpus-selection run.';
COMMENT ON TABLE solemd.paper_selection_summary IS
    'Compact per-paper selection summary refreshed from durable selection signals and release-scoped evidence counts.';
COMMENT ON TABLE solemd.corpus_wave_runs IS
    'One row per mapped-paper child-wave dispatch run feeding downstream hot-text acquisition.';
COMMENT ON TABLE solemd.corpus_wave_members IS
    'Deterministic mapped-paper membership for one dispatch wave plus enqueue progress.';

COMMENT ON COLUMN solemd.corpus_selection_runs.status IS
    'Corpus-selection lifecycle code from db/schema/enum-codes.yaml.corpus_selection_run_status.';
COMMENT ON COLUMN solemd.corpus_selection_runs.phase_started_at IS
    'Phase start timestamps keyed by phase name for resumable corpus-selection runs.';
COMMENT ON COLUMN solemd.corpus_selection_runs.plan_checksum IS
    'Stable SHA-256 digest of the validated corpus-selection plan manifest for resume/drift checks.';

COMMENT ON COLUMN solemd.corpus_selection_signals.phase_name IS
    'Selection phase that wrote the signal row; used for deterministic phase reruns.';
COMMENT ON COLUMN solemd.corpus_selection_signals.signal_kind IS
    'Stable signal-family name such as journal_match, pattern_match, vocab_entity_match, or mapped_journal_match.';
COMMENT ON COLUMN solemd.corpus_selection_signals.detail IS
    'Structured signal payload capturing matched alias, venue, concept, or other rule-family context.';

COMMENT ON COLUMN solemd.paper_selection_summary.current_status IS
    'Current corpus membership state mirrored from solemd.corpus.domain_status for the owning selection run.';
COMMENT ON COLUMN solemd.paper_selection_summary.mapped_family_keys IS
    'Distinct mapped-promotion family keys that promoted the paper during the owning selection run.';

COMMENT ON COLUMN solemd.corpus_wave_runs.status IS
    'Mapped-wave lifecycle code from db/schema/enum-codes.yaml.corpus_wave_run_status.';
COMMENT ON COLUMN solemd.corpus_wave_runs.phase_started_at IS
    'Phase start timestamps keyed by phase name for resumable child-wave dispatch runs.';
COMMENT ON COLUMN solemd.corpus_wave_runs.plan_checksum IS
    'Stable SHA-256 digest of the validated child-wave plan manifest for resume/drift checks.';

COMMENT ON COLUMN solemd.corpus_wave_members.actor_name IS
    'Downstream actor target for the wave member; initial slice dispatches to hot_text.acquire_for_paper.';

COMMENT ON COLUMN solemd.vocab_terms.source_asset_sha256 IS
    'SHA-256 of the source vocab_terms.tsv asset used for the current table refresh.';
COMMENT ON COLUMN solemd.vocab_term_aliases.normalized_alias IS
    'Normalized lookup key derived from alias text for fast warehouse-local PubTator joins.';
COMMENT ON COLUMN solemd.vocab_term_aliases.source_asset_sha256 IS
    'SHA-256 of the source vocab_aliases.tsv asset used for the current table refresh.';

COMMENT ON FUNCTION solemd.clean_venue(TEXT) IS
    'Normalize venue names for corpus journal matching by lowercasing, stripping trailing dots, subtitles, leading "the", and trailing parentheticals.';

GRANT INSERT, UPDATE, SELECT ON TABLE
    solemd.vocab_terms,
    solemd.vocab_term_aliases,
    solemd.corpus_selection_runs,
    solemd.corpus_selection_signals,
    solemd.paper_selection_summary,
    solemd.corpus_wave_runs,
    solemd.corpus_wave_members
TO engine_ingest_write;

GRANT DELETE ON TABLE
    solemd.vocab_term_aliases,
    solemd.vocab_terms,
    solemd.corpus_selection_signals,
    solemd.paper_selection_summary,
    solemd.corpus_wave_members
TO engine_ingest_write;

GRANT SELECT ON TABLE
    solemd.vocab_terms,
    solemd.vocab_term_aliases,
    solemd.corpus_selection_runs,
    solemd.corpus_selection_signals,
    solemd.paper_selection_summary,
    solemd.corpus_wave_runs,
    solemd.corpus_wave_members
TO engine_warehouse_read;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA solemd TO engine_ingest_write;

RESET ROLE;

REVOKE ALL ON FUNCTION solemd.clean_venue(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION solemd.clean_venue(TEXT) TO engine_warehouse_admin;
GRANT EXECUTE ON FUNCTION solemd.clean_venue(TEXT) TO engine_ingest_write;
GRANT EXECUTE ON FUNCTION solemd.clean_venue(TEXT) TO engine_warehouse_read;
GRANT EXECUTE ON FUNCTION solemd.clean_venue(TEXT) TO warehouse_grounding_reader;
