SET ROLE engine_warehouse_admin;

CREATE TABLE IF NOT EXISTS solemd.pmc_fulltext_fetch_runs (
    pmc_fulltext_fetch_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    requested_by TEXT,
    selector_version TEXT NOT NULL,
    source_order TEXT[] NOT NULL,
    limit_count INTEGER,
    requests_per_second NUMERIC(8, 3) NOT NULL DEFAULT 1.000,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'running',
    candidate_count BIGINT NOT NULL DEFAULT 0,
    unavailable_count BIGINT NOT NULL DEFAULT 0,
    fetched_count BIGINT NOT NULL DEFAULT 0,
    parsed_count BIGINT NOT NULL DEFAULT 0,
    promoted_count BIGINT NOT NULL DEFAULT 0,
    skipped_count BIGINT NOT NULL DEFAULT 0,
    failed_count BIGINT NOT NULL DEFAULT 0,
    run_config JSONB NOT NULL DEFAULT '{}'::JSONB,
    qa_detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_message TEXT,
    CONSTRAINT ck_pmc_fulltext_fetch_runs_status
        CHECK (status IN ('running', 'complete', 'failed', 'aborted')),
    CONSTRAINT ck_pmc_fulltext_fetch_runs_limit
        CHECK (limit_count IS NULL OR limit_count >= 1),
    CONSTRAINT ck_pmc_fulltext_fetch_runs_counts
        CHECK (
            candidate_count >= 0
            AND unavailable_count >= 0
            AND fetched_count >= 0
            AND parsed_count >= 0
            AND promoted_count >= 0
            AND skipped_count >= 0
            AND failed_count >= 0
        )
);
ALTER TABLE solemd.pmc_fulltext_fetch_runs SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.pmc_fulltext_documents (
    pmc_fulltext_document_id UUID PRIMARY KEY DEFAULT uuidv7(),
    pmc_fulltext_fetch_run_id UUID
        REFERENCES solemd.pmc_fulltext_fetch_runs (pmc_fulltext_fetch_run_id)
        ON DELETE SET NULL,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    pmcid TEXT NOT NULL,
    source_provider TEXT NOT NULL,
    source_url TEXT,
    source_package_path TEXT,
    source_checksum TEXT NOT NULL,
    parser_name TEXT NOT NULL,
    parser_version TEXT NOT NULL,
    license TEXT,
    license_url TEXT,
    license_source_provider TEXT,
    status TEXT NOT NULL,
    error_reason TEXT,
    fetched_at TIMESTAMPTZ,
    parsed_at TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT true,
    passage_count INTEGER NOT NULL DEFAULT 0,
    retrievable_passage_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pmc_fulltext_documents_source
        UNIQUE (pmcid, source_provider, source_checksum, parser_version),
    CONSTRAINT ck_pmc_fulltext_documents_provider
        CHECK (source_provider IN ('pmc_oa', 'pmc_oai', 'pmc_bioc')),
    CONSTRAINT ck_pmc_fulltext_documents_status
        CHECK (status IN ('parsed', 'unavailable', 'fetch_failed', 'parse_failed')),
    CONSTRAINT ck_pmc_fulltext_documents_counts
        CHECK (passage_count >= 0 AND retrievable_passage_count >= 0)
);
ALTER TABLE solemd.pmc_fulltext_documents SET (fillfactor = 90);
ALTER TABLE solemd.pmc_fulltext_documents ALTER COLUMN error_reason SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.pmc_fulltext_sections (
    pmc_fulltext_section_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmc_fulltext_document_id UUID NOT NULL
        REFERENCES solemd.pmc_fulltext_documents (pmc_fulltext_document_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    pmcid TEXT NOT NULL,
    section_ordinal INTEGER NOT NULL,
    parent_section_ordinal INTEGER,
    section_ordinal_path TEXT NOT NULL,
    title TEXT,
    section_label TEXT,
    depth INTEGER NOT NULL,
    section_role TEXT NOT NULL DEFAULT 'unknown',
    source_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pmc_fulltext_sections_ordinal
        UNIQUE (pmc_fulltext_document_id, section_ordinal),
    CONSTRAINT uq_pmc_fulltext_sections_path
        UNIQUE (pmc_fulltext_document_id, section_ordinal_path),
    CONSTRAINT ck_pmc_fulltext_sections_depth
        CHECK (depth >= 0),
    CONSTRAINT ck_pmc_fulltext_sections_role
        CHECK (
            section_role IN (
                'unknown',
                'abstract',
                'introduction',
                'methods',
                'results',
                'discussion',
                'conclusion',
                'supplement',
                'other'
            )
        )
);
ALTER TABLE solemd.pmc_fulltext_sections SET (fillfactor = 100);
ALTER TABLE solemd.pmc_fulltext_sections ALTER COLUMN title SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.pmc_fulltext_passages (
    pmc_fulltext_passage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmc_fulltext_document_id UUID NOT NULL
        REFERENCES solemd.pmc_fulltext_documents (pmc_fulltext_document_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    pmcid TEXT NOT NULL,
    section_ordinal INTEGER NOT NULL,
    section_ordinal_path TEXT NOT NULL,
    passage_ordinal INTEGER NOT NULL,
    passage_role TEXT NOT NULL,
    source_type TEXT,
    text TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    token_estimate INTEGER NOT NULL,
    text_checksum TEXT NOT NULL,
    is_retrievable BOOLEAN NOT NULL DEFAULT true,
    parser_name TEXT NOT NULL,
    parser_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pmc_fulltext_passages_ordinal
        UNIQUE (pmc_fulltext_document_id, passage_ordinal),
    CONSTRAINT ck_pmc_fulltext_passages_role
        CHECK (
            passage_role IN (
                'abstract',
                'body',
                'figure_caption',
                'table_caption',
                'table_body',
                'other'
            )
        ),
    CONSTRAINT ck_pmc_fulltext_passages_counts
        CHECK (char_count > 0 AND token_estimate >= 1)
);
ALTER TABLE solemd.pmc_fulltext_passages SET (fillfactor = 100);
ALTER TABLE solemd.pmc_fulltext_passages ALTER COLUMN text SET COMPRESSION lz4;

ALTER TABLE solemd.paper_selection_summary
    ADD COLUMN IF NOT EXISTS pmc_fulltext_document_id UUID
        REFERENCES solemd.pmc_fulltext_documents (pmc_fulltext_document_id)
        ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS pmc_fulltext_passage_count INTEGER,
    ADD COLUMN IF NOT EXISTS pmc_fulltext_promoted_at TIMESTAMPTZ;

ALTER TABLE solemd.paper_selection_summary
    DROP CONSTRAINT IF EXISTS ck_paper_selection_summary_pmc_passage_count;
ALTER TABLE solemd.paper_selection_summary
    ADD CONSTRAINT ck_paper_selection_summary_pmc_passage_count
        CHECK (pmc_fulltext_passage_count IS NULL OR pmc_fulltext_passage_count >= 0);

CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_fetch_runs_status_started
    ON solemd.pmc_fulltext_fetch_runs (status, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_documents_pmcid_status
    ON solemd.pmc_fulltext_documents (pmcid, status, source_provider, parser_version);
CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_documents_corpus_status
    ON solemd.pmc_fulltext_documents (corpus_id, status, parsed_at DESC);
CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_documents_provider_checksum
    ON solemd.pmc_fulltext_documents (source_provider, source_checksum, parser_version);
CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_documents_current
    ON solemd.pmc_fulltext_documents (pmcid, source_provider, parser_version, parsed_at DESC)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_sections_document_path
    ON solemd.pmc_fulltext_sections (pmc_fulltext_document_id, section_ordinal_path);
CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_sections_pmcid_role
    ON solemd.pmc_fulltext_sections (pmcid, section_role, section_ordinal_path);

CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_passages_retrieval
    ON solemd.pmc_fulltext_passages (
        corpus_id,
        pmcid,
        passage_role,
        section_ordinal_path,
        passage_ordinal
    )
    WHERE is_retrievable;
CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_passages_document_role
    ON solemd.pmc_fulltext_passages (
        pmc_fulltext_document_id,
        passage_role,
        section_ordinal_path
    );
CREATE INDEX IF NOT EXISTS idx_pmc_fulltext_passages_checksum
    ON solemd.pmc_fulltext_passages (
        pmc_fulltext_document_id,
        text_checksum
    );

CREATE INDEX IF NOT EXISTS idx_paper_selection_summary_pmc_fulltext_document
    ON solemd.paper_selection_summary (pmc_fulltext_document_id)
    WHERE pmc_fulltext_document_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_paper_selection_summary_pmcid_rescue
    ON solemd.paper_selection_summary (
        current_status,
        content_status,
        has_pmc_id,
        evidence_priority_score DESC,
        corpus_id
    )
    WHERE has_pmc_id;

GRANT INSERT, UPDATE, SELECT ON TABLE
    solemd.pmc_fulltext_fetch_runs,
    solemd.pmc_fulltext_documents,
    solemd.pmc_fulltext_sections,
    solemd.pmc_fulltext_passages,
    solemd.paper_selection_summary
TO engine_ingest_write;

GRANT DELETE ON TABLE
    solemd.pmc_fulltext_sections,
    solemd.pmc_fulltext_passages
TO engine_ingest_write;

GRANT SELECT ON TABLE
    solemd.pmc_fulltext_fetch_runs,
    solemd.pmc_fulltext_documents,
    solemd.pmc_fulltext_sections,
    solemd.pmc_fulltext_passages,
    solemd.paper_selection_summary
TO engine_warehouse_read;

GRANT USAGE, SELECT ON SEQUENCE
    solemd.pmc_fulltext_sections_pmc_fulltext_section_id_seq,
    solemd.pmc_fulltext_passages_pmc_fulltext_passage_id_seq
TO engine_ingest_write;

COMMENT ON TABLE solemd.pmc_fulltext_fetch_runs IS
    'Run-level ledger for PMC full-text enrichment over mapped PMCID papers.';
COMMENT ON TABLE solemd.pmc_fulltext_documents IS
    'One row per PMCID, source provider, source checksum, and parser version for licensed PMC full-text availability, fetch, parse, and materialization state.';
COMMENT ON TABLE solemd.pmc_fulltext_sections IS
    'Hierarchy-preserving normalized section rows produced from licensed PMC full-text parser adapters.';
COMMENT ON TABLE solemd.pmc_fulltext_passages IS
    'Retrievable PMC passage candidates with parser and checksum provenance.';

COMMENT ON COLUMN solemd.pmc_fulltext_fetch_runs.selector_version IS
    'Candidate selector key such as metadata-only-pmcid or mapped-pmcid.';
COMMENT ON COLUMN solemd.pmc_fulltext_fetch_runs.source_order IS
    'Ordered availability/fetch providers used by this run.';
COMMENT ON COLUMN solemd.pmc_fulltext_fetch_runs.status IS
    'PMC full-text run status from db/schema/enum-codes.yaml.pmc_fulltext_fetch_run_status.';
COMMENT ON COLUMN solemd.pmc_fulltext_documents.source_provider IS
    'PMC full-text source provider from db/schema/enum-codes.yaml.pmc_fulltext_source_provider.';
COMMENT ON COLUMN solemd.pmc_fulltext_documents.status IS
    'PMC full-text document lifecycle status from db/schema/enum-codes.yaml.pmc_fulltext_document_status.';
COMMENT ON COLUMN solemd.pmc_fulltext_documents.license_source_provider IS
    'PMC availability source that supplied license provenance before text parsing.';
COMMENT ON COLUMN solemd.pmc_fulltext_documents.source_checksum IS
    'SHA-256 checksum of the fetched text payload or deterministic negative availability payload.';
COMMENT ON COLUMN solemd.pmc_fulltext_documents.is_current IS
    'True for the latest parsed or negative document state for one PMCID/provider/parser path.';
COMMENT ON COLUMN solemd.pmc_fulltext_sections.section_ordinal_path IS
    'Stable dot-delimited hierarchy path such as 0001.0002.';
COMMENT ON COLUMN solemd.pmc_fulltext_sections.section_role IS
    'Normalized PMC section role from db/schema/enum-codes.yaml.pmc_fulltext_section_role; unknown preserves unmapped source variation.';
COMMENT ON COLUMN solemd.pmc_fulltext_passages.passage_role IS
    'Normalized retrievable PMC passage role from db/schema/enum-codes.yaml.pmc_fulltext_passage_role.';
COMMENT ON COLUMN solemd.pmc_fulltext_passages.text_checksum IS
    'SHA-256 checksum over parser version, PMCID, passage role, section path, ordinal, and normalized passage text.';
COMMENT ON COLUMN solemd.paper_selection_summary.pmc_fulltext_document_id IS
    'Current PMC full-text document that promoted this summary row to fulltext_ready.';
COMMENT ON COLUMN solemd.paper_selection_summary.pmc_fulltext_passage_count IS
    'Retrievable passage count present when PMC full-text promotion was applied.';
COMMENT ON COLUMN solemd.paper_selection_summary.pmc_fulltext_promoted_at IS
    'Timestamp when the guarded PMC full-text lane promoted this summary row.';

RESET ROLE;
