"use client";
/**
 * D3 smoke test — `<model-viewer>` displaying an ethanol .glb
 * generated by the SMILES pipeline (`make molecule "CCO" --name ethanol`).
 *
 * Gating: the `<model-viewer>` custom element is registered by a
 * side-effect import. Rendering the element before
 * `customElements.define()` runs makes the browser see an unknown
 * HTMLElement and never upgrade it. The component waits for the import
 * to resolve before mounting the element.
 *
 * Brand defaults baked in:
 * - tone-mapping="neutral" (Khronos PBR Neutral, scientific accuracy)
 * - environment-image="neutral" (flat IBL, no colored kickers)
 * - exposure 0.85 (pastels don't blow out)
 * - shadow-intensity 0.6 (visible depth without drama)
 * - auto-rotate with a 500 ms delay (calm, not frantic)
 */
import { useEffect, useState } from "react";

export default function ModelViewerDemo() {
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let cancelled = false;
    import("@google/model-viewer").then(() => {
      if (!cancelled) setReady(true);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  if (!ready) {
    return (
      <div
        className="flex h-[360px] w-full items-center justify-center"
        style={{ color: "var(--text-secondary)" }}
        aria-live="polite"
      >
        Loading 3D viewer…
      </div>
    );
  }

  return (
    <div className="h-[360px] w-full">
      {/* @ts-expect-error — web component is not typed in React 19 */}
      <model-viewer
        src="/animations/_assets/glb/ethanol.glb"
        alt="Ethanol molecule (C2H6O) — 3D ball-and-stick model, CPK colored"
        auto-rotate
        auto-rotate-delay="500"
        rotation-per-second="18deg"
        camera-controls
        interaction-prompt="none"
        environment-image="neutral"
        tone-mapping="neutral"
        exposure="0.85"
        shadow-intensity="0.6"
        shadow-softness="0.9"
        style={{
          width: "100%",
          height: "100%",
          background: "var(--surface)",
        } as React.CSSProperties}
      />
    </div>
  );
}
