"use client";
/**
 * D3 smoke test — `<model-viewer>` displaying an ethanol .glb
 * generated by the SMILES pipeline (`make molecule "CCO" --name ethanol`).
 */
import { useEffect } from "react";

export default function ModelViewerDemo() {
  useEffect(() => {
    void import("@google/model-viewer");
  }, []);

  return (
    <div className="h-[360px] w-full">
      {/* @ts-expect-error — web component is not typed in React 19 */}
      <model-viewer
        src="/animations/_assets/glb/ethanol.glb"
        alt="Ethanol molecule"
        auto-rotate
        auto-rotate-delay="500"
        camera-controls
        environment-image="neutral"
        exposure="0.85"
        shadow-intensity="0.6"
        style={{
          width: "100%",
          height: "100%",
          background: "var(--surface)",
        } as React.CSSProperties}
      />
    </div>
  );
}
