SET ROLE engine_warehouse_admin;

CREATE TABLE IF NOT EXISTS solemd.source_releases (
    source_release_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_published_at TIMESTAMPTZ,
    source_ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    manifest_checksum TEXT,
    manifest_uri TEXT,
    source_name TEXT NOT NULL,
    source_release_key TEXT NOT NULL,
    release_status TEXT NOT NULL DEFAULT 'planned',
    CONSTRAINT uq_source_releases_natural UNIQUE (source_name, source_release_key),
    CONSTRAINT ck_source_releases_status
        CHECK (release_status IN ('planned', 'ingesting', 'loaded', 'retired'))
);
ALTER TABLE solemd.source_releases SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.ingest_runs (
    ingest_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    advisory_lock_key BIGINT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    status SMALLINT NOT NULL DEFAULT 1,
    requested_status SMALLINT,
    manifest_uri TEXT,
    error_message TEXT,
    last_loaded_family TEXT,
    families_loaded TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    plan_manifest JSONB,
    phase_started_at JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_ingest_runs_status
        CHECK (status BETWEEN 1 AND 7),
    CONSTRAINT ck_ingest_runs_requested_status
        CHECK (requested_status IS NULL OR requested_status BETWEEN 1 AND 2)
);
ALTER TABLE solemd.ingest_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.ingest_file_tasks (
    ingest_run_id UUID NOT NULL
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE CASCADE,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    family_name TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_byte_count BIGINT NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    input_bytes_read BIGINT NOT NULL DEFAULT 0,
    rows_written BIGINT NOT NULL DEFAULT 0,
    stage_row_count INTEGER NOT NULL DEFAULT 0,
    claim_token UUID,
    enqueued_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_error TEXT,
    PRIMARY KEY (ingest_run_id, family_name, file_name),
    CONSTRAINT ck_ingest_file_tasks_status
        CHECK (status BETWEEN 1 AND 4),
    CONSTRAINT ck_ingest_file_tasks_attempt_count
        CHECK (attempt_count >= 0)
);
ALTER TABLE solemd.ingest_file_tasks SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.corpus (
    corpus_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    admission_reason TEXT NOT NULL,
    domain_status TEXT NOT NULL DEFAULT 'corpus',
    CONSTRAINT ck_corpus_domain_status
        CHECK (domain_status IN ('corpus', 'mapped', 'retired'))
);
ALTER TABLE solemd.corpus SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.venues (
    venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_venue_id TEXT,
    issn TEXT,
    eissn TEXT,
    display_name TEXT NOT NULL,
    normalized_name TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(display_name)
    ) STORED,
    curated_family SMALLINT
);
ALTER TABLE solemd.venues SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.authors (
    author_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_author_id TEXT,
    orcid TEXT,
    display_name TEXT NOT NULL,
    normalized_name TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(display_name)
    ) STORED
);
ALTER TABLE solemd.authors SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.papers (
    corpus_id BIGINT PRIMARY KEY
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    venue_id BIGINT
        REFERENCES solemd.venues (venue_id)
        ON DELETE SET NULL,
    publication_date DATE,
    year SMALLINT,
    language SMALLINT,
    article_type SMALLINT,
    is_open_access BOOLEAN,
    is_retracted BOOLEAN NOT NULL DEFAULT false,
    pmid INTEGER,
    doi_norm TEXT,
    pmc_id TEXT,
    s2_paper_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE solemd.papers SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.paper_text (
    corpus_id BIGINT PRIMARY KEY
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    title_hash BYTEA,
    abstract_hash BYTEA,
    text_availability SMALLINT NOT NULL DEFAULT 0,
    title TEXT NOT NULL,
    normalized_title_key TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(title)
    ) STORED,
    abstract TEXT,
    tldr TEXT,
    fts_vector TSVECTOR GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(abstract, '')), 'B')
    ) STORED,
    CONSTRAINT ck_paper_text_availability
        CHECK (text_availability BETWEEN 0 AND 2)
);
ALTER TABLE solemd.paper_text SET (fillfactor = 90);
ALTER TABLE solemd.paper_text ALTER COLUMN abstract SET COMPRESSION lz4;
ALTER TABLE solemd.paper_text ALTER COLUMN tldr SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.paper_authors (
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    author_id BIGINT NOT NULL
        REFERENCES solemd.authors (author_id)
        ON DELETE RESTRICT,
    author_ordinal SMALLINT NOT NULL,
    affiliation_text TEXT,
    PRIMARY KEY (corpus_id, author_ordinal)
);
ALTER TABLE solemd.paper_authors SET (fillfactor = 100);
ALTER TABLE solemd.paper_authors ALTER COLUMN affiliation_text SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.paper_citations (
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    reference_checksum TEXT NOT NULL,
    cited_corpus_id BIGINT
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE SET NULL,
    cited_s2_paper_id TEXT,
    linkage_status SMALLINT NOT NULL DEFAULT 1,
    is_influential BOOLEAN NOT NULL DEFAULT false,
    intent_raw TEXT,
    PRIMARY KEY (corpus_id, reference_checksum),
    CONSTRAINT ck_paper_citations_linkage
        CHECK (linkage_status BETWEEN 1 AND 3)
);
ALTER TABLE solemd.paper_citations SET (fillfactor = 100);
ALTER TABLE solemd.paper_citations ALTER COLUMN intent_raw SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.paper_chunk_versions (
    chunk_version_key UUID PRIMARY KEY DEFAULT uuidv7(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    policy_key TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT false,
    is_default BOOLEAN NOT NULL DEFAULT false,
    notes TEXT
);
ALTER TABLE solemd.paper_chunk_versions SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.graph_runs (
    graph_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    built_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    source_release_watermark INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    layout_policy_version TEXT NOT NULL,
    embedding_model_key SMALLINT,
    status SMALLINT NOT NULL DEFAULT 1,
    qa_summary JSONB,
    CONSTRAINT ck_graph_runs_status
        CHECK (status BETWEEN 1 AND 5)
);
ALTER TABLE solemd.graph_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.s2_papers_raw (
    paper_id TEXT PRIMARY KEY,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    corpus_id BIGINT
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE SET NULL,
    source_venue_id TEXT,
    pmid INTEGER,
    doi_norm TEXT,
    pmc_id TEXT,
    title TEXT,
    abstract TEXT,
    tldr TEXT,
    venue_raw TEXT,
    year INTEGER,
    publication_date DATE,
    is_open_access BOOLEAN,
    payload_checksum TEXT,
    last_seen_run_id UUID
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE SET NULL
);
ALTER TABLE solemd.s2_papers_raw SET (fillfactor = 100);
ALTER TABLE solemd.s2_papers_raw ALTER COLUMN abstract SET COMPRESSION lz4;
ALTER TABLE solemd.s2_papers_raw ALTER COLUMN tldr SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.s2_paper_authors_raw (
    paper_id TEXT NOT NULL
        REFERENCES solemd.s2_papers_raw (paper_id)
        ON DELETE CASCADE,
    author_ordinal INTEGER NOT NULL,
    source_author_id TEXT,
    name_raw TEXT NOT NULL,
    affiliation_raw TEXT,
    PRIMARY KEY (paper_id, author_ordinal)
);
ALTER TABLE solemd.s2_paper_authors_raw SET (fillfactor = 100);
ALTER TABLE solemd.s2_paper_authors_raw ALTER COLUMN affiliation_raw SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.s2_authors_raw (
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    source_author_id TEXT NOT NULL,
    orcid TEXT,
    display_name TEXT NOT NULL,
    last_seen_run_id UUID
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE SET NULL,
    PRIMARY KEY (source_release_id, source_author_id)
);
ALTER TABLE solemd.s2_authors_raw SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.s2_paper_reference_metrics_raw (
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    citing_paper_id TEXT NOT NULL,
    reference_out_count INTEGER NOT NULL DEFAULT 0,
    influential_reference_count INTEGER NOT NULL DEFAULT 0,
    linked_reference_count INTEGER NOT NULL DEFAULT 0,
    orphan_reference_count INTEGER NOT NULL DEFAULT 0,
    last_seen_run_id UUID
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE SET NULL,
    PRIMARY KEY (source_release_id, citing_paper_id)
);
ALTER TABLE solemd.s2_paper_reference_metrics_raw SET (fillfactor = 100);

CREATE UNLOGGED TABLE IF NOT EXISTS solemd.s2_paper_reference_metrics_stage (
    ingest_run_id UUID NOT NULL,
    source_release_id INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    batch_ordinal INTEGER NOT NULL,
    citing_paper_id TEXT NOT NULL,
    reference_out_count INTEGER NOT NULL DEFAULT 0,
    influential_reference_count INTEGER NOT NULL DEFAULT 0,
    linked_reference_count INTEGER NOT NULL DEFAULT 0,
    orphan_reference_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT s2_paper_reference_metrics_stage_pk PRIMARY KEY (
        ingest_run_id,
        source_release_id,
        file_name,
        batch_ordinal,
        citing_paper_id
    )
);
ALTER TABLE solemd.s2_paper_reference_metrics_stage SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.s2_paper_reference_metrics_file_checkpoints (
    ingest_run_id UUID NOT NULL
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE CASCADE,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    file_name TEXT NOT NULL,
    file_byte_count BIGINT NOT NULL DEFAULT 0,
    stage_row_count INTEGER NOT NULL DEFAULT 0,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (ingest_run_id, source_release_id, file_name)
);
ALTER TABLE solemd.s2_paper_reference_metrics_file_checkpoints SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.s2_paper_references_raw (
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    citing_paper_id TEXT NOT NULL,
    reference_checksum TEXT NOT NULL,
    cited_paper_id TEXT,
    linkage_status SMALLINT NOT NULL DEFAULT 1,
    is_influential BOOLEAN NOT NULL DEFAULT false,
    intent_raw TEXT,
    PRIMARY KEY (source_release_id, reference_checksum),
    CONSTRAINT ck_s2_paper_references_raw_linkage
        CHECK (linkage_status BETWEEN 1 AND 3)
);
ALTER TABLE solemd.s2_paper_references_raw SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.s2_paper_assets_raw (
    paper_id TEXT NOT NULL
        REFERENCES solemd.s2_papers_raw (paper_id)
        ON DELETE CASCADE,
    asset_kind TEXT NOT NULL,
    asset_url TEXT NOT NULL,
    content_type TEXT,
    availability_raw TEXT,
    asset_checksum TEXT,
    PRIMARY KEY (paper_id, asset_kind, asset_url)
);
ALTER TABLE solemd.s2_paper_assets_raw SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.s2orc_documents_raw (
    paper_id TEXT PRIMARY KEY,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    text_hash BYTEA NOT NULL,
    document_payload TEXT NOT NULL,
    last_seen_run_id UUID
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE SET NULL
);
ALTER TABLE solemd.s2orc_documents_raw SET (fillfactor = 100);
ALTER TABLE solemd.s2orc_documents_raw ALTER COLUMN document_payload SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS pubtator.entity_annotations_stage (
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pmid INTEGER NOT NULL,
    start_offset INTEGER NOT NULL,
    end_offset INTEGER NOT NULL,
    entity_type SMALLINT NOT NULL,
    mention_text TEXT NOT NULL,
    concept_id_raw TEXT NOT NULL,
    resource SMALLINT NOT NULL,
    corpus_id BIGINT
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE SET NULL,
    last_seen_run_id UUID
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE SET NULL,
    PRIMARY KEY (
        source_release_id,
        pmid,
        start_offset,
        end_offset,
        entity_type,
        concept_id_raw,
        resource
    ),
    CONSTRAINT ck_pubtator_entity_annotations_stage_entity_type
        CHECK (entity_type BETWEEN 1 AND 6),
    CONSTRAINT ck_pubtator_entity_annotations_stage_resource
        CHECK (resource BETWEEN 1 AND 2),
    CONSTRAINT ck_pubtator_entity_annotations_stage_offset_span
        CHECK (end_offset >= start_offset)
);
ALTER TABLE pubtator.entity_annotations_stage SET (fillfactor = 100);
ALTER TABLE pubtator.entity_annotations_stage ALTER COLUMN mention_text SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS pubtator.entity_annotations (
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    start_offset INTEGER NOT NULL,
    end_offset INTEGER NOT NULL,
    pmid INTEGER,
    entity_type SMALLINT NOT NULL,
    mention_text TEXT NOT NULL,
    concept_id_raw TEXT NOT NULL,
    resource SMALLINT NOT NULL,
    PRIMARY KEY (
        corpus_id,
        start_offset,
        end_offset,
        entity_type,
        concept_id_raw,
        resource
    ),
    CONSTRAINT ck_pubtator_entity_annotations_entity_type
        CHECK (entity_type BETWEEN 1 AND 6),
    CONSTRAINT ck_pubtator_entity_annotations_resource
        CHECK (resource BETWEEN 1 AND 2),
    CONSTRAINT ck_pubtator_entity_annotations_offset_span
        CHECK (end_offset >= start_offset)
) PARTITION BY HASH (corpus_id);
ALTER TABLE pubtator.entity_annotations ALTER COLUMN mention_text SET COMPRESSION lz4;

DO $$
DECLARE
    partition_idx INTEGER;
    partition_suffix TEXT;
BEGIN
    FOR partition_idx IN 0..31 LOOP
        partition_suffix := lpad(partition_idx::TEXT, 2, '0');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS pubtator.entity_annotations_p%s PARTITION OF pubtator.entity_annotations FOR VALUES WITH (modulus 32, remainder %s)',
            partition_suffix,
            partition_idx
        );
        EXECUTE format(
            'ALTER TABLE pubtator.entity_annotations_p%s SET (fillfactor = 100)',
            partition_suffix
        );
    END LOOP;
END
$$;

CREATE TABLE IF NOT EXISTS pubtator.relations_stage (
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pmid INTEGER NOT NULL,
    relation_type SMALLINT NOT NULL,
    subject_entity_id TEXT NOT NULL,
    object_entity_id TEXT NOT NULL,
    subject_type SMALLINT NOT NULL,
    object_type SMALLINT NOT NULL,
    relation_source SMALLINT NOT NULL,
    corpus_id BIGINT
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE SET NULL,
    last_seen_run_id UUID
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE SET NULL,
    PRIMARY KEY (
        source_release_id,
        pmid,
        subject_entity_id,
        relation_type,
        object_entity_id,
        relation_source
    ),
    CONSTRAINT ck_pubtator_relations_stage_relation_type
        CHECK (relation_type BETWEEN 1 AND 12),
    CONSTRAINT ck_pubtator_relations_stage_subject_type
        CHECK (subject_type BETWEEN 1 AND 6),
    CONSTRAINT ck_pubtator_relations_stage_object_type
        CHECK (object_type BETWEEN 1 AND 6),
    CONSTRAINT ck_pubtator_relations_stage_relation_source
        CHECK (relation_source BETWEEN 1 AND 2)
);
ALTER TABLE pubtator.relations_stage SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS pubtator.relations (
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pmid INTEGER,
    relation_type SMALLINT NOT NULL,
    subject_entity_id TEXT NOT NULL,
    object_entity_id TEXT NOT NULL,
    subject_type SMALLINT NOT NULL,
    object_type SMALLINT NOT NULL,
    relation_source SMALLINT NOT NULL,
    PRIMARY KEY (corpus_id, subject_entity_id, relation_type, object_entity_id),
    CONSTRAINT ck_pubtator_relations_relation_type
        CHECK (relation_type BETWEEN 1 AND 12),
    CONSTRAINT ck_pubtator_relations_subject_type
        CHECK (subject_type BETWEEN 1 AND 6),
    CONSTRAINT ck_pubtator_relations_object_type
        CHECK (object_type BETWEEN 1 AND 6),
    CONSTRAINT ck_pubtator_relations_relation_source
        CHECK (relation_source BETWEEN 1 AND 2)
) PARTITION BY HASH (corpus_id);

DO $$
DECLARE
    partition_idx INTEGER;
    partition_suffix TEXT;
BEGIN
    FOR partition_idx IN 0..31 LOOP
        partition_suffix := lpad(partition_idx::TEXT, 2, '0');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS pubtator.relations_p%s PARTITION OF pubtator.relations FOR VALUES WITH (modulus 32, remainder %s)',
            partition_suffix,
            partition_idx
        );
        EXECUTE format(
            'ALTER TABLE pubtator.relations_p%s SET (fillfactor = 100)',
            partition_suffix
        );
    END LOOP;
END
$$;

RESET ROLE;
