SET ROLE engine_warehouse_admin;

CREATE TABLE IF NOT EXISTS solemd.source_releases (
    source_release_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_published_at TIMESTAMPTZ,
    source_ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    manifest_checksum TEXT,
    manifest_uri TEXT,
    source_name TEXT NOT NULL,
    source_release_key TEXT NOT NULL,
    release_status TEXT NOT NULL DEFAULT 'planned',
    CONSTRAINT uq_source_releases_natural UNIQUE (source_name, source_release_key),
    CONSTRAINT ck_source_releases_status
        CHECK (release_status IN ('planned', 'ingesting', 'loaded', 'retired'))
);
ALTER TABLE solemd.source_releases SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.ingest_runs (
    ingest_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    advisory_lock_key BIGINT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    status SMALLINT NOT NULL DEFAULT 1,
    requested_status SMALLINT,
    manifest_uri TEXT,
    error_message TEXT,
    last_loaded_family TEXT,
    families_loaded TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    plan_manifest JSONB,
    phase_started_at JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_ingest_runs_status
        CHECK (status BETWEEN 1 AND 7),
    CONSTRAINT ck_ingest_runs_requested_status
        CHECK (requested_status IS NULL OR requested_status BETWEEN 1 AND 2)
);
ALTER TABLE solemd.ingest_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.corpus (
    corpus_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    admission_reason TEXT NOT NULL,
    domain_status TEXT NOT NULL DEFAULT 'candidate',
    CONSTRAINT ck_corpus_domain_status
        CHECK (domain_status IN ('candidate', 'mapped', 'retired'))
);
ALTER TABLE solemd.corpus SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.venues (
    venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issn TEXT,
    eissn TEXT,
    display_name TEXT NOT NULL,
    normalized_name TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(display_name)
    ) STORED,
    curated_family SMALLINT
);
ALTER TABLE solemd.venues SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.authors (
    author_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orcid TEXT,
    display_name TEXT NOT NULL,
    normalized_name TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(display_name)
    ) STORED
);
ALTER TABLE solemd.authors SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.papers (
    corpus_id BIGINT PRIMARY KEY
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    venue_id BIGINT
        REFERENCES solemd.venues (venue_id)
        ON DELETE SET NULL,
    publication_date DATE,
    year SMALLINT,
    language SMALLINT,
    article_type SMALLINT,
    is_open_access BOOLEAN,
    is_retracted BOOLEAN NOT NULL DEFAULT false,
    pmid INTEGER,
    doi_norm TEXT,
    pmc_id TEXT,
    s2_paper_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE solemd.papers SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.paper_text (
    corpus_id BIGINT PRIMARY KEY
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    title_hash BYTEA,
    abstract_hash BYTEA,
    text_availability SMALLINT NOT NULL DEFAULT 0,
    title TEXT NOT NULL,
    normalized_title_key TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(title)
    ) STORED,
    abstract TEXT,
    tldr TEXT,
    fts_vector TSVECTOR GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(abstract, '')), 'B')
    ) STORED,
    CONSTRAINT ck_paper_text_availability
        CHECK (text_availability BETWEEN 0 AND 2)
);
ALTER TABLE solemd.paper_text SET (fillfactor = 90);
ALTER TABLE solemd.paper_text ALTER COLUMN abstract SET COMPRESSION lz4;
ALTER TABLE solemd.paper_text ALTER COLUMN tldr SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.paper_authors (
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    author_id BIGINT NOT NULL
        REFERENCES solemd.authors (author_id)
        ON DELETE RESTRICT,
    author_ordinal SMALLINT NOT NULL,
    affiliation_text TEXT,
    PRIMARY KEY (corpus_id, author_ordinal)
);
ALTER TABLE solemd.paper_authors SET (fillfactor = 100);
ALTER TABLE solemd.paper_authors ALTER COLUMN affiliation_text SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.paper_chunk_versions (
    chunk_version_key UUID PRIMARY KEY DEFAULT uuidv7(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    policy_key TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT false,
    is_default BOOLEAN NOT NULL DEFAULT false,
    notes TEXT
);
ALTER TABLE solemd.paper_chunk_versions SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.graph_runs (
    graph_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    built_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    source_release_watermark INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    layout_policy_version TEXT NOT NULL,
    embedding_model_key SMALLINT,
    status SMALLINT NOT NULL DEFAULT 1,
    qa_summary JSONB,
    CONSTRAINT ck_graph_runs_status
        CHECK (status BETWEEN 1 AND 5)
);
ALTER TABLE solemd.graph_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.s2_papers_raw (
    paper_id TEXT PRIMARY KEY,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    corpus_id BIGINT
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE SET NULL,
    pmid INTEGER,
    doi_norm TEXT,
    pmc_id TEXT,
    title TEXT,
    abstract TEXT,
    venue_raw TEXT,
    year INTEGER,
    publication_date DATE,
    payload_checksum TEXT,
    last_seen_run_id UUID
        REFERENCES solemd.ingest_runs (ingest_run_id)
        ON DELETE SET NULL
);
ALTER TABLE solemd.s2_papers_raw SET (fillfactor = 100);
ALTER TABLE solemd.s2_papers_raw ALTER COLUMN abstract SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.s2_paper_authors_raw (
    paper_id TEXT NOT NULL
        REFERENCES solemd.s2_papers_raw (paper_id)
        ON DELETE CASCADE,
    author_ordinal INTEGER NOT NULL,
    source_author_id TEXT,
    name_raw TEXT NOT NULL,
    affiliation_raw TEXT,
    PRIMARY KEY (paper_id, author_ordinal)
);
ALTER TABLE solemd.s2_paper_authors_raw SET (fillfactor = 100);
ALTER TABLE solemd.s2_paper_authors_raw ALTER COLUMN affiliation_raw SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.s2_paper_references_raw (
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    citing_paper_id TEXT NOT NULL,
    cited_paper_id TEXT NOT NULL,
    linkage_status SMALLINT NOT NULL DEFAULT 1,
    is_influential BOOLEAN NOT NULL DEFAULT false,
    intent_raw TEXT,
    PRIMARY KEY (source_release_id, citing_paper_id, cited_paper_id),
    CONSTRAINT ck_s2_paper_references_raw_linkage
        CHECK (linkage_status BETWEEN 1 AND 3)
);
ALTER TABLE solemd.s2_paper_references_raw SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.s2_paper_assets_raw (
    paper_id TEXT NOT NULL
        REFERENCES solemd.s2_papers_raw (paper_id)
        ON DELETE CASCADE,
    asset_kind TEXT NOT NULL,
    asset_url TEXT NOT NULL,
    content_type TEXT,
    availability_raw TEXT,
    asset_checksum TEXT,
    PRIMARY KEY (paper_id, asset_kind, asset_url)
);
ALTER TABLE solemd.s2_paper_assets_raw SET (fillfactor = 100);

RESET ROLE;
