SET ROLE engine_warehouse_admin;

CREATE TABLE IF NOT EXISTS solemd.vocab_terms (
    term_id UUID PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    normalized_name TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(canonical_name)
    ) STORED,
    category TEXT NOT NULL,
    umls_cui TEXT,
    rxnorm_cui TEXT,
    semantic_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    semantic_groups TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    organ_systems TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    source_asset_sha256 TEXT NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE solemd.vocab_terms SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.vocab_term_aliases (
    term_id UUID NOT NULL
        REFERENCES solemd.vocab_terms (term_id)
        ON DELETE CASCADE,
    alias TEXT NOT NULL,
    normalized_alias TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(alias)
    ) STORED,
    alias_type TEXT,
    quality_score INTEGER,
    is_preferred BOOLEAN NOT NULL DEFAULT false,
    umls_cui TEXT,
    source_asset_sha256 TEXT NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (term_id, alias)
);
ALTER TABLE solemd.vocab_term_aliases SET (fillfactor = 95);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_runs (
    corpus_selection_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    advisory_lock_key BIGINT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pt3_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    requested_by TEXT,
    trigger TEXT NOT NULL DEFAULT 'manual',
    status SMALLINT NOT NULL DEFAULT 1,
    error_message TEXT,
    last_completed_phase TEXT,
    phases_completed TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    plan_checksum TEXT NOT NULL,
    plan_manifest JSONB NOT NULL,
    phase_started_at JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_corpus_selection_runs_trigger
        CHECK (trigger IN ('manual', 'dispatch')),
    CONSTRAINT ck_corpus_selection_runs_status
        CHECK (status BETWEEN 1 AND 8)
);
ALTER TABLE solemd.corpus_selection_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_signals (
    corpus_selection_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    phase_name TEXT NOT NULL,
    signal_kind TEXT NOT NULL,
    family_key TEXT,
    match_key TEXT,
    match_value TEXT,
    signal_count INTEGER NOT NULL DEFAULT 1,
    contributes_to_corpus BOOLEAN NOT NULL DEFAULT false,
    contributes_to_mapped BOOLEAN NOT NULL DEFAULT false,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_corpus_selection_signals_signal_count
        CHECK (signal_count >= 1)
);
ALTER TABLE solemd.corpus_selection_signals SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.paper_selection_summary (
    corpus_id BIGINT PRIMARY KEY
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    current_status TEXT NOT NULL,
    primary_admission_reason TEXT,
    normalized_venue TEXT NOT NULL DEFAULT '',
    publication_year SMALLINT,
    has_journal_match BOOLEAN NOT NULL DEFAULT false,
    has_pattern_match BOOLEAN NOT NULL DEFAULT false,
    has_vocab_entity_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_journal_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_pattern_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_entity_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_relation_match BOOLEAN NOT NULL DEFAULT false,
    journal_signal_count INTEGER NOT NULL DEFAULT 0,
    pattern_signal_count INTEGER NOT NULL DEFAULT 0,
    vocab_entity_signal_count INTEGER NOT NULL DEFAULT 0,
    entity_annotation_count INTEGER NOT NULL DEFAULT 0,
    relation_count INTEGER NOT NULL DEFAULT 0,
    mapped_signal_count INTEGER NOT NULL DEFAULT 0,
    mapped_entity_signal_count INTEGER NOT NULL DEFAULT 0,
    mapped_relation_signal_count INTEGER NOT NULL DEFAULT 0,
    mapped_family_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    has_open_access BOOLEAN NOT NULL DEFAULT false,
    has_pmc_id BOOLEAN NOT NULL DEFAULT false,
    has_locator_candidate BOOLEAN NOT NULL DEFAULT false,
    has_abstract BOOLEAN NOT NULL DEFAULT false,
    reference_out_count INTEGER NOT NULL DEFAULT 0,
    influential_reference_count INTEGER NOT NULL DEFAULT 0,
    mapped_priority_score INTEGER NOT NULL DEFAULT 0,
    evidence_priority_score INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_paper_selection_summary_status
        CHECK (current_status IN ('corpus', 'mapped', 'retired'))
);
ALTER TABLE solemd.paper_selection_summary SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.corpus_wave_runs (
    corpus_wave_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    advisory_lock_key BIGINT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE RESTRICT,
    wave_policy_key TEXT NOT NULL,
    requested_by TEXT,
    status SMALLINT NOT NULL DEFAULT 1,
    error_message TEXT,
    last_completed_phase TEXT,
    phases_completed TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    plan_checksum TEXT NOT NULL,
    plan_manifest JSONB NOT NULL,
    phase_started_at JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_corpus_wave_runs_status
        CHECK (status BETWEEN 1 AND 5)
);
ALTER TABLE solemd.corpus_wave_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.corpus_wave_members (
    corpus_wave_run_id UUID NOT NULL
        REFERENCES solemd.corpus_wave_runs (corpus_wave_run_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    member_ordinal INTEGER NOT NULL,
    priority_score INTEGER NOT NULL DEFAULT 0,
    enqueued_at TIMESTAMPTZ,
    actor_name TEXT NOT NULL DEFAULT 'evidence.acquire_for_paper',
    selection_detail JSONB,
    PRIMARY KEY (corpus_wave_run_id, corpus_id),
    CONSTRAINT ck_corpus_wave_members_member_ordinal
        CHECK (member_ordinal >= 1),
    CONSTRAINT ck_corpus_wave_members_priority_score
        CHECK (priority_score >= 0)
);
ALTER TABLE solemd.corpus_wave_members SET (fillfactor = 100);

RESET ROLE;
