SET ROLE engine_warehouse_admin;

CREATE TABLE IF NOT EXISTS solemd.vocab_terms (
    term_id UUID PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    normalized_name TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(canonical_name)
    ) STORED,
    category TEXT NOT NULL,
    umls_cui TEXT,
    rxnorm_cui TEXT,
    semantic_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    semantic_groups TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    organ_systems TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    source_asset_sha256 TEXT NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE solemd.vocab_terms SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.vocab_term_aliases (
    term_id UUID NOT NULL
        REFERENCES solemd.vocab_terms (term_id)
        ON DELETE CASCADE,
    alias TEXT NOT NULL,
    normalized_alias TEXT GENERATED ALWAYS AS (
        solemd.normalize_lookup_key(alias)
    ) STORED,
    alias_type TEXT,
    quality_score INTEGER,
    is_preferred BOOLEAN NOT NULL DEFAULT false,
    umls_cui TEXT,
    source_asset_sha256 TEXT NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (term_id, alias)
);
ALTER TABLE solemd.vocab_term_aliases SET (fillfactor = 95);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_runs (
    corpus_selection_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    advisory_lock_key BIGINT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pt3_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    requested_by TEXT,
    trigger TEXT NOT NULL DEFAULT 'manual',
    status SMALLINT NOT NULL DEFAULT 1,
    error_message TEXT,
    last_completed_phase TEXT,
    phases_completed TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    plan_checksum TEXT NOT NULL,
    plan_manifest JSONB NOT NULL,
    phase_started_at JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_corpus_selection_runs_trigger
        CHECK (trigger IN ('manual', 'dispatch')),
    CONSTRAINT ck_corpus_selection_runs_status
        CHECK (status BETWEEN 1 AND 8)
);
ALTER TABLE solemd.corpus_selection_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_signals (
    corpus_selection_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    phase_name TEXT NOT NULL,
    signal_kind TEXT NOT NULL,
    family_key TEXT,
    match_key TEXT,
    match_value TEXT,
    signal_count INTEGER NOT NULL DEFAULT 1,
    contributes_to_corpus BOOLEAN NOT NULL DEFAULT false,
    contributes_to_mapped BOOLEAN NOT NULL DEFAULT false,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_corpus_selection_signals_signal_count
        CHECK (signal_count >= 1)
);
ALTER TABLE solemd.corpus_selection_signals SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.paper_corpus_assignments (
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    paper_id TEXT NOT NULL,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    assigned_by_run_id UUID
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE SET NULL,
    selector_version TEXT NOT NULL,
    admission_reason TEXT NOT NULL DEFAULT 'corpus_pending',
    entity_signal_checksum TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (s2_source_release_id, paper_id)
);
ALTER TABLE solemd.paper_corpus_assignments SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_artifacts (
    corpus_selection_artifact_id UUID PRIMARY KEY DEFAULT uuidv7(),
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE CASCADE,
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pt3_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    phase_name TEXT NOT NULL,
    artifact_kind TEXT NOT NULL,
    storage_schema TEXT NOT NULL,
    storage_table TEXT NOT NULL,
    is_logged BOOLEAN NOT NULL DEFAULT false,
    status TEXT NOT NULL DEFAULT 'building',
    plan_checksum TEXT NOT NULL,
    row_count BIGINT,
    byte_size BIGINT,
    detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    dropped_at TIMESTAMPTZ,
    error_message TEXT,
    CONSTRAINT ck_corpus_selection_artifacts_status
        CHECK (status IN ('building', 'complete', 'failed', 'stale', 'dropped')),
    CONSTRAINT uq_corpus_selection_artifacts_run_kind
        UNIQUE (corpus_selection_run_id, artifact_kind)
);
ALTER TABLE solemd.corpus_selection_artifacts SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_chunks (
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE CASCADE,
    phase_name TEXT NOT NULL,
    bucket_id INTEGER NOT NULL,
    bucket_count INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    row_counts JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_message TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (corpus_selection_run_id, phase_name, bucket_id),
    CONSTRAINT ck_corpus_selection_chunks_status
        CHECK (status IN ('pending', 'running', 'complete', 'failed')),
    CONSTRAINT ck_corpus_selection_chunks_bucket
        CHECK (bucket_id >= 0 AND bucket_count > 0 AND bucket_id < bucket_count),
    CONSTRAINT ck_corpus_selection_chunks_attempts
        CHECK (attempts >= 0)
);
ALTER TABLE solemd.corpus_selection_chunks SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.paper_entity_signal_builds (
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pt3_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    entity_signal_checksum TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'building',
    row_count BIGINT,
    byte_size BIGINT,
    detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    PRIMARY KEY (
        s2_source_release_id,
        pt3_source_release_id,
        entity_signal_checksum
    ),
    CONSTRAINT ck_paper_entity_signal_builds_status
        CHECK (status IN ('building', 'complete', 'failed', 'stale'))
);
ALTER TABLE solemd.paper_entity_signal_builds SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.paper_entity_signals (
    paper_entity_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    pt3_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    entity_signal_checksum TEXT NOT NULL,
    paper_id TEXT NOT NULL,
    pmid INTEGER NOT NULL,
    entity_type SMALLINT NOT NULL,
    concept_id_raw TEXT NOT NULL,
    term_id UUID,
    term_canonical_name TEXT,
    term_category TEXT,
    matched_alias TEXT,
    rule_canonical_name TEXT,
    rule_family_key TEXT,
    rule_confidence TEXT,
    rule_min_reference_count INTEGER NOT NULL DEFAULT 0,
    matched_mention_text TEXT,
    signal_count INTEGER NOT NULL,
    reference_out_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_paper_entity_signals_match
        CHECK (
            (term_id IS NOT NULL AND rule_family_key IS NULL)
            OR (term_id IS NULL AND rule_family_key IS NOT NULL)
        ),
    CONSTRAINT ck_paper_entity_signals_signal_count
        CHECK (signal_count >= 1),
    CONSTRAINT ck_paper_entity_signals_reference_out_count
        CHECK (reference_out_count >= 0),
    CONSTRAINT ck_paper_entity_signals_rule_min_reference_count
        CHECK (rule_min_reference_count >= 0)
);
ALTER TABLE solemd.paper_entity_signals SET (fillfactor = 100);
ALTER TABLE solemd.paper_entity_signals ALTER COLUMN concept_id_raw SET COMPRESSION lz4;
ALTER TABLE solemd.paper_entity_signals ALTER COLUMN matched_mention_text SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.paper_selection_summary (
    corpus_id BIGINT PRIMARY KEY
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    current_status TEXT NOT NULL,
    primary_admission_reason TEXT,
    normalized_venue TEXT NOT NULL DEFAULT '',
    publication_year SMALLINT,
    has_journal_match BOOLEAN NOT NULL DEFAULT false,
    has_pattern_match BOOLEAN NOT NULL DEFAULT false,
    has_vocab_entity_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_journal_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_pattern_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_entity_match BOOLEAN NOT NULL DEFAULT false,
    has_mapped_relation_match BOOLEAN NOT NULL DEFAULT false,
    journal_signal_count INTEGER NOT NULL DEFAULT 0,
    pattern_signal_count INTEGER NOT NULL DEFAULT 0,
    vocab_entity_signal_count INTEGER NOT NULL DEFAULT 0,
    entity_annotation_count INTEGER NOT NULL DEFAULT 0,
    raw_pubtator_entity_annotation_count INTEGER NOT NULL DEFAULT 0,
    curated_entity_signal_count INTEGER NOT NULL DEFAULT 0,
    relation_count INTEGER NOT NULL DEFAULT 0,
    raw_pubtator_relation_count INTEGER NOT NULL DEFAULT 0,
    mapped_signal_count INTEGER NOT NULL DEFAULT 0,
    mapped_entity_signal_count INTEGER NOT NULL DEFAULT 0,
    mapped_relation_signal_count INTEGER NOT NULL DEFAULT 0,
    mapped_family_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    has_open_access BOOLEAN NOT NULL DEFAULT false,
    has_pmc_id BOOLEAN NOT NULL DEFAULT false,
    has_locator_candidate BOOLEAN NOT NULL DEFAULT false,
    has_abstract BOOLEAN NOT NULL DEFAULT false,
    reference_out_count INTEGER NOT NULL DEFAULT 0,
    influential_reference_count INTEGER NOT NULL DEFAULT 0,
    incoming_citation_count INTEGER NOT NULL DEFAULT 0,
    influential_citation_count INTEGER NOT NULL DEFAULT 0,
    s2_fields_of_study TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    s2_publication_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    open_access_pdf_status TEXT,
    publication_venue_type TEXT,
    rag_candidate BOOLEAN NOT NULL DEFAULT false,
    rag_eligible BOOLEAN NOT NULL DEFAULT false,
    content_status TEXT NOT NULL DEFAULT 'metadata_only',
    relevance_band TEXT NOT NULL DEFAULT 'weak_candidate',
    topic_tracks TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    organ_system_tracks TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    publication_type_tracks TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    mesh_major_tracks TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    has_cl_bridge BOOLEAN NOT NULL DEFAULT false,
    quality_warnings JSONB NOT NULL DEFAULT '{}'::JSONB,
    mapped_priority_score INTEGER NOT NULL DEFAULT 0,
    evidence_priority_score INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_paper_selection_summary_status
        CHECK (current_status IN ('corpus', 'mapped', 'retired')),
    CONSTRAINT ck_paper_selection_summary_content_status
        CHECK (
            content_status IN (
                'fulltext_ready',
                'abstract_ready',
                'metadata_only',
                'missing_text'
            )
        ),
    CONSTRAINT ck_paper_selection_summary_relevance_band
        CHECK (
            relevance_band IN (
                'high_confidence',
                'clinical_bridge',
                'venue_supported',
                'weak_candidate',
                'low_confidence'
            )
        )
);
ALTER TABLE solemd.paper_selection_summary SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.pubmed_metadata_fetch_runs (
    pubmed_metadata_fetch_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    corpus_selection_run_id UUID
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE SET NULL,
    requested_by TEXT,
    status TEXT NOT NULL DEFAULT 'running',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    max_papers INTEGER,
    detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_message TEXT,
    CONSTRAINT ck_pubmed_metadata_fetch_runs_status
        CHECK (status IN ('running', 'complete', 'failed', 'aborted')),
    CONSTRAINT ck_pubmed_metadata_fetch_runs_max_papers
        CHECK (max_papers IS NULL OR max_papers >= 1)
);
ALTER TABLE solemd.pubmed_metadata_fetch_runs SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.pubmed_metadata_fetch_tasks (
    pubmed_metadata_fetch_run_id UUID NOT NULL
        REFERENCES solemd.pubmed_metadata_fetch_runs (pubmed_metadata_fetch_run_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    pmid INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (pubmed_metadata_fetch_run_id, pmid),
    CONSTRAINT ck_pubmed_metadata_fetch_tasks_status
        CHECK (status IN ('pending', 'running', 'complete', 'not_found', 'failed')),
    CONSTRAINT ck_pubmed_metadata_fetch_tasks_attempts
        CHECK (attempts >= 0)
);
ALTER TABLE solemd.pubmed_metadata_fetch_tasks SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.pubmed_metadata (
    pmid INTEGER PRIMARY KEY,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_name TEXT NOT NULL DEFAULT 'pubmed_efetch',
    response_checksum TEXT NOT NULL,
    article_title TEXT,
    abstract_text TEXT,
    abstract_hash TEXT,
    language_codes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    publication_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    citation_subsets TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    mesh_headings JSONB NOT NULL DEFAULT '[]'::JSONB,
    mesh_major_terms TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    keywords TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    grant_count INTEGER NOT NULL DEFAULT 0,
    has_grant BOOLEAN NOT NULL DEFAULT false,
    chemicals JSONB NOT NULL DEFAULT '[]'::JSONB,
    comments_corrections JSONB NOT NULL DEFAULT '[]'::JSONB,
    has_retraction BOOLEAN NOT NULL DEFAULT false,
    has_erratum BOOLEAN NOT NULL DEFAULT false,
    publication_status TEXT,
    structured_abstract JSONB NOT NULL DEFAULT '[]'::JSONB,
    raw_detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_pubmed_metadata_grant_count
        CHECK (grant_count >= 0)
);
ALTER TABLE solemd.pubmed_metadata SET (fillfactor = 90);
ALTER TABLE solemd.pubmed_metadata ALTER COLUMN article_title SET COMPRESSION lz4;
ALTER TABLE solemd.pubmed_metadata ALTER COLUMN abstract_text SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.s2_graph_enrichment_runs (
    s2_graph_enrichment_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    corpus_selection_run_id UUID
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE SET NULL,
    s2_source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    requested_by TEXT,
    status TEXT NOT NULL DEFAULT 'running',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    max_papers INTEGER,
    detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_message TEXT,
    CONSTRAINT ck_s2_graph_enrichment_runs_status
        CHECK (status IN ('running', 'complete', 'failed', 'aborted')),
    CONSTRAINT ck_s2_graph_enrichment_runs_max_papers
        CHECK (max_papers IS NULL OR max_papers >= 1)
);
ALTER TABLE solemd.s2_graph_enrichment_runs SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.s2_graph_enrichment_tasks (
    s2_graph_enrichment_run_id UUID NOT NULL
        REFERENCES solemd.s2_graph_enrichment_runs (s2_graph_enrichment_run_id)
        ON DELETE CASCADE,
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    paper_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (s2_graph_enrichment_run_id, paper_id),
    CONSTRAINT ck_s2_graph_enrichment_tasks_status
        CHECK (status IN ('pending', 'running', 'complete', 'not_found', 'failed')),
    CONSTRAINT ck_s2_graph_enrichment_tasks_attempts
        CHECK (attempts >= 0)
);
ALTER TABLE solemd.s2_graph_enrichment_tasks SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.s2_paper_enrichment (
    source_release_id INTEGER NOT NULL
        REFERENCES solemd.source_releases (source_release_id)
        ON DELETE RESTRICT,
    paper_id TEXT NOT NULL,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    response_checksum TEXT NOT NULL,
    citation_count INTEGER NOT NULL DEFAULT 0,
    influential_citation_count INTEGER NOT NULL DEFAULT 0,
    publication_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    fields_of_study TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    s2_fields_of_study JSONB NOT NULL DEFAULT '[]'::JSONB,
    open_access_pdf JSONB NOT NULL DEFAULT '{}'::JSONB,
    open_access_pdf_status TEXT,
    publication_venue JSONB NOT NULL DEFAULT '{}'::JSONB,
    publication_venue_type TEXT,
    external_ids JSONB NOT NULL DEFAULT '{}'::JSONB,
    journal JSONB NOT NULL DEFAULT '{}'::JSONB,
    is_open_access BOOLEAN,
    year INTEGER,
    publication_date DATE,
    raw_detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    PRIMARY KEY (source_release_id, paper_id),
    CONSTRAINT ck_s2_paper_enrichment_citation_count
        CHECK (citation_count >= 0),
    CONSTRAINT ck_s2_paper_enrichment_influential_count
        CHECK (influential_citation_count >= 0)
);
ALTER TABLE solemd.s2_paper_enrichment SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.corpus_selection_summary_refresh_runs (
    corpus_selection_summary_refresh_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    s2_graph_enrichment_run_id UUID
        REFERENCES solemd.s2_graph_enrichment_runs (s2_graph_enrichment_run_id)
        ON DELETE SET NULL,
    pubmed_metadata_fetch_run_id UUID
        REFERENCES solemd.pubmed_metadata_fetch_runs (pubmed_metadata_fetch_run_id)
        ON DELETE SET NULL,
    requested_by TEXT,
    status TEXT NOT NULL DEFAULT 'running',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    plan_checksum TEXT NOT NULL,
    summary_row_count BIGINT,
    chunk_count INTEGER,
    s2_enrichment_row_count BIGINT,
    s2_not_found_count BIGINT,
    pubmed_metadata_row_count BIGINT,
    pubmed_not_found_count BIGINT,
    pre_refresh_detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    post_refresh_detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_message TEXT,
    CONSTRAINT ck_corpus_selection_summary_refresh_runs_status
        CHECK (status IN ('running', 'complete', 'failed')),
    CONSTRAINT ck_corpus_selection_summary_refresh_runs_counts
        CHECK (
            (summary_row_count IS NULL OR summary_row_count >= 0)
            AND (chunk_count IS NULL OR chunk_count >= 1)
            AND (s2_enrichment_row_count IS NULL OR s2_enrichment_row_count >= 0)
            AND (s2_not_found_count IS NULL OR s2_not_found_count >= 0)
            AND (pubmed_metadata_row_count IS NULL OR pubmed_metadata_row_count >= 0)
            AND (pubmed_not_found_count IS NULL OR pubmed_not_found_count >= 0)
        )
);
ALTER TABLE solemd.corpus_selection_summary_refresh_runs SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.corpus_quality_audit_runs (
    corpus_quality_audit_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE RESTRICT,
    selector_version TEXT NOT NULL,
    requested_by TEXT,
    status TEXT NOT NULL DEFAULT 'running',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    plan_checksum TEXT NOT NULL,
    sample_size INTEGER NOT NULL DEFAULT 12,
    summary_row_count BIGINT,
    mapped_row_count BIGINT,
    rag_eligible_row_count BIGINT,
    distributions JSONB NOT NULL DEFAULT '{}'::JSONB,
    relation_diagnostic JSONB NOT NULL DEFAULT '{}'::JSONB,
    top_signals JSONB NOT NULL DEFAULT '{}'::JSONB,
    samples JSONB NOT NULL DEFAULT '{}'::JSONB,
    findings JSONB NOT NULL DEFAULT '[]'::JSONB,
    error_message TEXT,
    CONSTRAINT ck_corpus_quality_audit_runs_status
        CHECK (status IN ('running', 'complete', 'failed')),
    CONSTRAINT ck_corpus_quality_audit_runs_counts
        CHECK (
            sample_size BETWEEN 1 AND 50
            AND (summary_row_count IS NULL OR summary_row_count >= 0)
            AND (mapped_row_count IS NULL OR mapped_row_count >= 0)
            AND (rag_eligible_row_count IS NULL OR rag_eligible_row_count >= 0)
        )
);
ALTER TABLE solemd.corpus_quality_audit_runs SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.corpus_wave_runs (
    corpus_wave_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    advisory_lock_key BIGINT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    corpus_selection_run_id UUID NOT NULL
        REFERENCES solemd.corpus_selection_runs (corpus_selection_run_id)
        ON DELETE RESTRICT,
    wave_policy_key TEXT NOT NULL,
    requested_by TEXT,
    status SMALLINT NOT NULL DEFAULT 1,
    error_message TEXT,
    last_completed_phase TEXT,
    phases_completed TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    plan_checksum TEXT NOT NULL,
    plan_manifest JSONB NOT NULL,
    phase_started_at JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ck_corpus_wave_runs_status
        CHECK (status BETWEEN 1 AND 5)
);
ALTER TABLE solemd.corpus_wave_runs SET (fillfactor = 80);

CREATE TABLE IF NOT EXISTS solemd.corpus_wave_members (
    corpus_wave_run_id UUID NOT NULL
        REFERENCES solemd.corpus_wave_runs (corpus_wave_run_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    member_ordinal INTEGER NOT NULL,
    priority_score INTEGER NOT NULL DEFAULT 0,
    enqueued_at TIMESTAMPTZ,
    actor_name TEXT NOT NULL DEFAULT 'evidence.acquire_for_paper',
    selection_detail JSONB,
    PRIMARY KEY (corpus_wave_run_id, corpus_id),
    CONSTRAINT ck_corpus_wave_members_member_ordinal
        CHECK (member_ordinal >= 1),
    CONSTRAINT ck_corpus_wave_members_priority_score
        CHECK (priority_score >= 0)
);
ALTER TABLE solemd.corpus_wave_members SET (fillfactor = 100);

CREATE TABLE IF NOT EXISTS solemd.pmc_fulltext_fetch_runs (
    pmc_fulltext_fetch_run_id UUID PRIMARY KEY DEFAULT uuidv7(),
    requested_by TEXT,
    selector_version TEXT NOT NULL,
    source_order TEXT[] NOT NULL,
    limit_count INTEGER,
    requests_per_second NUMERIC(8, 3) NOT NULL DEFAULT 1.000,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'running',
    candidate_count BIGINT NOT NULL DEFAULT 0,
    unavailable_count BIGINT NOT NULL DEFAULT 0,
    fetched_count BIGINT NOT NULL DEFAULT 0,
    parsed_count BIGINT NOT NULL DEFAULT 0,
    promoted_count BIGINT NOT NULL DEFAULT 0,
    skipped_count BIGINT NOT NULL DEFAULT 0,
    failed_count BIGINT NOT NULL DEFAULT 0,
    run_config JSONB NOT NULL DEFAULT '{}'::JSONB,
    qa_detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_message TEXT,
    CONSTRAINT ck_pmc_fulltext_fetch_runs_status
        CHECK (status IN ('running', 'complete', 'failed', 'aborted')),
    CONSTRAINT ck_pmc_fulltext_fetch_runs_limit
        CHECK (limit_count IS NULL OR limit_count >= 1),
    CONSTRAINT ck_pmc_fulltext_fetch_runs_counts
        CHECK (
            candidate_count >= 0
            AND unavailable_count >= 0
            AND fetched_count >= 0
            AND parsed_count >= 0
            AND promoted_count >= 0
            AND skipped_count >= 0
            AND failed_count >= 0
        )
);
ALTER TABLE solemd.pmc_fulltext_fetch_runs SET (fillfactor = 90);

CREATE TABLE IF NOT EXISTS solemd.pmc_fulltext_documents (
    pmc_fulltext_document_id UUID PRIMARY KEY DEFAULT uuidv7(),
    pmc_fulltext_fetch_run_id UUID
        REFERENCES solemd.pmc_fulltext_fetch_runs (pmc_fulltext_fetch_run_id)
        ON DELETE SET NULL,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    pmcid TEXT NOT NULL,
    source_provider TEXT NOT NULL,
    source_url TEXT,
    source_package_path TEXT,
    source_checksum TEXT NOT NULL,
    parser_name TEXT NOT NULL,
    parser_version TEXT NOT NULL,
    license TEXT,
    license_url TEXT,
    license_source_provider TEXT,
    status TEXT NOT NULL,
    error_reason TEXT,
    fetched_at TIMESTAMPTZ,
    parsed_at TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT true,
    passage_count INTEGER NOT NULL DEFAULT 0,
    retrievable_passage_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pmc_fulltext_documents_source
        UNIQUE (pmcid, source_provider, source_checksum, parser_version),
    CONSTRAINT ck_pmc_fulltext_documents_provider
        CHECK (source_provider IN ('pmc_oa', 'pmc_oai', 'pmc_bioc')),
    CONSTRAINT ck_pmc_fulltext_documents_status
        CHECK (status IN ('parsed', 'unavailable', 'fetch_failed', 'parse_failed')),
    CONSTRAINT ck_pmc_fulltext_documents_counts
        CHECK (passage_count >= 0 AND retrievable_passage_count >= 0)
);
ALTER TABLE solemd.pmc_fulltext_documents SET (fillfactor = 90);
ALTER TABLE solemd.pmc_fulltext_documents ALTER COLUMN error_reason SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.pmc_fulltext_sections (
    pmc_fulltext_section_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmc_fulltext_document_id UUID NOT NULL
        REFERENCES solemd.pmc_fulltext_documents (pmc_fulltext_document_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    pmcid TEXT NOT NULL,
    section_ordinal INTEGER NOT NULL,
    parent_section_ordinal INTEGER,
    section_ordinal_path TEXT NOT NULL,
    title TEXT,
    section_label TEXT,
    depth INTEGER NOT NULL,
    section_type TEXT,
    section_role TEXT NOT NULL DEFAULT 'unknown',
    section_role_codes TEXT[] NOT NULL DEFAULT ARRAY['unknown']::TEXT[],
    section_role_confidence NUMERIC(4, 3) NOT NULL DEFAULT 0.000,
    section_role_source TEXT NOT NULL DEFAULT 'unknown',
    source_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pmc_fulltext_sections_ordinal
        UNIQUE (pmc_fulltext_document_id, section_ordinal),
    CONSTRAINT uq_pmc_fulltext_sections_path
        UNIQUE (pmc_fulltext_document_id, section_ordinal_path),
    CONSTRAINT ck_pmc_fulltext_sections_depth
        CHECK (depth >= 0),
    CONSTRAINT ck_pmc_fulltext_sections_role
        CHECK (
            section_role IN (
                'unknown',
                'abstract',
                'introduction',
                'methods',
                'materials',
                'subjects_population',
                'results',
                'discussion',
                'conclusion',
                'limitations',
                'case_report',
                'data_availability',
                'ethics',
                'funding',
                'conflict_of_interest',
                'acknowledgments',
                'author_contributions',
                'supplement',
                'references',
                'other'
            )
        ),
    CONSTRAINT ck_pmc_fulltext_sections_role_codes
        CHECK (
            cardinality(section_role_codes) >= 1
            AND section_role_codes <@ ARRAY[
                'unknown',
                'abstract',
                'introduction',
                'methods',
                'materials',
                'subjects_population',
                'results',
                'discussion',
                'conclusion',
                'limitations',
                'case_report',
                'data_availability',
                'ethics',
                'funding',
                'conflict_of_interest',
                'acknowledgments',
                'author_contributions',
                'supplement',
                'references',
                'other'
            ]::TEXT[]
        ),
    CONSTRAINT ck_pmc_fulltext_sections_role_confidence
        CHECK (section_role_confidence >= 0.000 AND section_role_confidence <= 1.000),
    CONSTRAINT ck_pmc_fulltext_sections_role_source
        CHECK (btrim(section_role_source) <> '')
);
ALTER TABLE solemd.pmc_fulltext_sections SET (fillfactor = 100);
ALTER TABLE solemd.pmc_fulltext_sections ALTER COLUMN title SET COMPRESSION lz4;

CREATE TABLE IF NOT EXISTS solemd.pmc_fulltext_passages (
    pmc_fulltext_passage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmc_fulltext_document_id UUID NOT NULL
        REFERENCES solemd.pmc_fulltext_documents (pmc_fulltext_document_id)
        ON DELETE CASCADE,
    corpus_id BIGINT NOT NULL
        REFERENCES solemd.corpus (corpus_id)
        ON DELETE CASCADE,
    pmcid TEXT NOT NULL,
    section_ordinal INTEGER NOT NULL,
    section_ordinal_path TEXT NOT NULL,
    passage_ordinal INTEGER NOT NULL,
    passage_role TEXT NOT NULL,
    source_type TEXT,
    text TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    token_estimate INTEGER NOT NULL,
    text_checksum TEXT NOT NULL,
    is_retrievable BOOLEAN NOT NULL DEFAULT true,
    parser_name TEXT NOT NULL,
    parser_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pmc_fulltext_passages_ordinal
        UNIQUE (pmc_fulltext_document_id, passage_ordinal),
    CONSTRAINT ck_pmc_fulltext_passages_role
        CHECK (
            passage_role IN (
                'abstract',
                'body',
                'figure_caption',
                'table_caption',
                'table_body',
                'other'
            )
        ),
    CONSTRAINT ck_pmc_fulltext_passages_counts
        CHECK (char_count > 0 AND token_estimate >= 1)
);
ALTER TABLE solemd.pmc_fulltext_passages SET (fillfactor = 100);
ALTER TABLE solemd.pmc_fulltext_passages ALTER COLUMN text SET COMPRESSION lz4;

ALTER TABLE solemd.paper_selection_summary
    ADD COLUMN IF NOT EXISTS pmc_fulltext_document_id UUID
        REFERENCES solemd.pmc_fulltext_documents (pmc_fulltext_document_id)
        ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS pmc_fulltext_passage_count INTEGER,
    ADD COLUMN IF NOT EXISTS pmc_fulltext_promoted_at TIMESTAMPTZ;

ALTER TABLE solemd.paper_selection_summary
    DROP CONSTRAINT IF EXISTS ck_paper_selection_summary_pmc_passage_count;
ALTER TABLE solemd.paper_selection_summary
    ADD CONSTRAINT ck_paper_selection_summary_pmc_passage_count
        CHECK (pmc_fulltext_passage_count IS NULL OR pmc_fulltext_passage_count >= 0);

RESET ROLE;
